# Acomodo mapper

## Librerías

In [2]:
import pandas as pd
import numpy as np
import random

import plotly
import requests
from bs4 import BeautifulSoup
import ruptures as rpt
import yfinance as yf

import plotly.graph_objects as go
import matplotlib.pyplot as plt

import kmapper as km
import subprocess
import sys
import networkx as nx
subprocess.check_call([sys.executable, "-m", "pip", "install", "plotly", "nbformat>=4.2.0"])
import sklearn.cluster

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import pairwise_distances
from sklearn.cluster import DBSCAN, KMeans
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

## Recolección de datos

### Sacar tickers S&P500

In [3]:

# URL de la lista del S&P 500
url = "https://www.slickcharts.com/sp500"


# Hacer la petición con headers para evitar bloqueos
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
}
response = requests.get(url, headers=headers)
response.raise_for_status()  # Raise exception for bad status codes

# Parsear el HTML
soup = BeautifulSoup(response.text, 'html.parser')

# Encontrar la tabla
table = soup.find('table')

if table:
    # Leer la tabla con pandas
    df = pd.read_html(str(table))[0]
    
    # Extraer los tickers
    if 'Symbol' in df.columns:
        tickers = df['Symbol'].tolist()
        print(f"Found {len(tickers)} tickers")
        print("First 10 tickers:", tickers[:10])
    else:
        print("Available columns:", df.columns.tolist())

    # Extraer los pesos
    if 'Weight' in df.columns:
        weights = df['Weight'].tolist()
        print(f"Found {len(weights)} weights")
        print("First 10 weights:", weights[:10])
    else:
        print("Available columns:", df.columns.tolist())
else:
    print("No table found on the page")

# En la lista de ticker, reemplazar los "." por "-"
tickers = [ticker.replace('.', '-') for ticker in tickers]
print("Tickers after replacement:", tickers[:10])

Found 503 tickers
First 10 tickers: ['NVDA', 'AAPL', 'MSFT', 'AMZN', 'AVGO', 'GOOGL', 'META', 'GOOG', 'TSLA', 'BRK.B']
Found 503 weights
First 10 weights: ['8.02%', '6.66%', '6.30%', '4.33%', '2.87%', '2.86%', '2.73%', '2.67%', '2.38%', '1.66%']
Tickers after replacement: ['NVDA', 'AAPL', 'MSFT', 'AMZN', 'AVGO', 'GOOGL', 'META', 'GOOG', 'TSLA', 'BRK-B']

### Información financiera

In [4]:
# =======================================================
# 📊 RECOPILACIÓN DE INFORMACIÓN FUNDAMENTAL DE TICKERS
# =======================================================

print("🔍 Recopilando información detallada de todos los tickers del S&P 500...")
print("=" * 80)

ticker_info_db = {}
failed_tickers = []


for idx, ticker in enumerate(tickers, 1):
    try:
        stock = yf.Ticker(ticker)
        info = stock.info
        
        # Extraer información relevante
        ticker_info_db[ticker] = {
            # Información básica
            'sector': info.get('sector', 'Unknown'),
            'industry': info.get('industry', 'Unknown'),
            'market_cap': info.get('marketCap', None),
            'country': info.get('country', 'Unknown'),
            'full_name': info.get('longName', ticker),
            
            # Métricas de valoración
            'pe_ratio': info.get('trailingPE', None),
            'forward_pe': info.get('forwardPE', None),
            'peg_ratio': info.get('pegRatio', None),
            'price_to_book': info.get('priceToBook', None),
            'price_to_sales': info.get('priceToSalesTrailing12Months', None),
            'enterprise_value': info.get('enterpriseValue', None),
            'ev_to_ebitda': info.get('enterpriseToEbitda', None),
            
            # Dividendos
            'dividend_yield': info.get('dividendYield', None),
            'dividend_rate': info.get('dividendRate', None),
            'payout_ratio': info.get('payoutRatio', None),
            'five_year_avg_dividend_yield': info.get('fiveYearAvgDividendYield', None),
            
            # Rentabilidad
            'profit_margins': info.get('profitMargins', None),
            'operating_margins': info.get('operatingMargins', None),
            'gross_margins': info.get('grossMargins', None),
            'roe': info.get('returnOnEquity', None),
            'roa': info.get('returnOnAssets', None),
            
            # Crecimiento
            'revenue_growth': info.get('revenueGrowth', None),
            'earnings_growth': info.get('earningsGrowth', None),
            'earnings_quarterly_growth': info.get('earningsQuarterlyGrowth', None),
            
            # Riesgo y volatilidad
            'beta': info.get('beta', None),
            '52week_high': info.get('fiftyTwoWeekHigh', None),
            '52week_low': info.get('fiftyTwoWeekLow', None),
            '52week_change': info.get('52WeekChange', None),
            
            # Liquidez y deuda
            'current_ratio': info.get('currentRatio', None),
            'quick_ratio': info.get('quickRatio', None),
            'debt_to_equity': info.get('debtToEquity', None),
            'total_debt': info.get('totalDebt', None),
            'total_cash': info.get('totalCash', None),
            
            # Analistas y recomendaciones
            'recommendation': info.get('recommendationKey', 'Unknown'),
            'recommendation_mean': info.get('recommendationMean', None),
            'target_mean_price': info.get('targetMeanPrice', None),
            'target_high_price': info.get('targetHighPrice', None),
            'target_low_price': info.get('targetLowPrice', None),
            'number_of_analysts': info.get('numberOfAnalystOpinions', None),
            
            # Información adicional
            'employees': info.get('fullTimeEmployees', None),
            'exchange': info.get('exchange', 'Unknown'),
            'quote_type': info.get('quoteType', 'Unknown'),
        }
        
        
    except Exception as e:
        failed_tickers.append(ticker)
        ticker_info_db[ticker] = {
            'sector': 'Unknown',
            'industry': 'Unknown',
            'error': str(e)
        }

print(f"\n{'='*80}")
print(f"📊 RESUMEN DE RECOPILACIÓN:")
if failed_tickers:
    print(f"   Tickers fallidos: {', '.join(failed_tickers[:10])}{'...' if len(failed_tickers) > 10 else ''}")

# Crear DataFrame para análisis fácil
ticker_info_df = pd.DataFrame.from_dict(ticker_info_db, orient='index')

print(f"\n DataFrame de información creado: {ticker_info_df.shape}")


# Guardar en CSV para uso posterior
ticker_info_df.to_csv('sp500_ticker_info_database.csv')
print("\n Base de datos guardada en 'sp500_ticker_info_database.csv'")

# Mostrar primeras filas
print("\n Primeras filas de la base de datos:")
display(ticker_info_df.head(10))

🔍 Recopilando información detallada de todos los tickers del S&P 500...
================================================================================

================================================================================
📊 RESUMEN DE RECOPILACIÓN:

 DataFrame de información creado: (503, 42)

 Base de datos guardada en 'sp500_ticker_info_database.csv'

 Primeras filas de la base de datos:

,sector,industry,market_cap,country,full_name,pe_ratio,forward_pe,peg_ratio,price_to_book,price_to_sales,...,total_cash,recommendation,recommendation_mean,target_mean_price,target_high_price,target_low_price,number_of_analysts,employees,exchange,quote_type
NVDA,Technology,Semiconductors,4939762892800,United States,NVIDIA Corporation,57.639206,49.245148,None,49.328957,29.898457,...,5.679100e+10,strong_buy,1.34375,225.49614,320.0,100.0,57.0,36000.0,NMS,EQUITY
AAPL,Technology,Consumer Electronics,4027681603584,United States,Apple Inc.,41.246200,32.659443,None,61.250280,9.856669,...,5.537200e+10,buy,2.04167,256.00660,320.0,180.0,41.0,150000.0,NMS,EQUITY
MSFT,Technology,Software - Infrastructure,3908020207616,United States,Microsoft Corporation,37.340910,35.167892,None,11.379102,13.871804,...,9.456500e+10,strong_buy,1.21053,622.81885,730.0,483.0,52.0,228000.0,NMS,EQUITY
AMZN,Consumer Cyclical,Internet Retail,2376782315520,United States,"Amazon.com, Inc.",33.972560,36.237396,None,7.117626,3.547235,...,9.318000e+10,strong_buy,1.28986,267.92062,306.0,230.0,63.0,1546000.0,NMS,EQUITY
AVGO,Technology,Semiconductors,1777828757504,United States,Broadcom Inc.,96.530770,61.016210,None,6.357036,29.667068,...,1.110500e+10,strong_buy,1.28261,392.38165,475.0,273.4,41.0,37000.0,NMS,EQUITY
GOOGL,Communication Services,Internet Content & Information,3407559262208,United States,Alphabet Inc.,27.786774,31.415180,None,10.573211,9.174929,...,9.514800e+10,buy,1.50746,297.28537,350.0,185.0,52.0,187103.0,NMS,EQUITY
META,Communication Services,Internet Content & Information,1674266935296,United States,"Meta Platforms, Inc.",29.450730,26.342688,None,9.246896,9.363700,...,4.707100e+10,strong_buy,1.41176,850.59880,1117.0,616.0,60.0,75945.0,NMS,EQUITY
GOOG,Communication Services,Internet Content & Information,3405202325504,United States,Alphabet Inc.,27.828232,31.497208,None,10.588986,9.168582,...,9.514800e+10,strong_buy,1.50000,292.10000,345.0,185.0,17.0,187103.0,NMS,EQUITY
TSLA,Consumer Cyclical,Auto Manufacturers,1463693082624,United States,"Tesla, Inc.",307.762270,135.833330,None,18.293291,15.305314,...,4.164700e+10,hold,2.61702,391.31805,600.0,120.0,41.0,125665.0,NMS,EQUITY
BRK-B,Financial Services,Insurance - Diversified,1031941586944,United States,Berkshire Hathaway Inc.,16.410150,23.830677,None,0.001031,2.787894,...,3.440910e+11,none,NaN,519.66670,593.0,479.0,3.0,392400.0,NYQ,EQUITY

### Datos históricos separados

In [5]:

START_DATE='2025-04-01'
END_DATE='2025-10-08'
AN_DATE='2025-08-01'

In [6]:
# -----------------------------
# Descargar precios históricos
# -----------------------------
# -----------------------------
# Descargar precios históricos
# -----------------------------
all_tickers_data = yf.download(tickers, start=START_DATE, end=END_DATE, auto_adjust=True)['Close']
all_tickers_data = all_tickers_data.dropna(axis=1)  # eliminar columnas con datos faltantes

# DIVIDIR EN DOS PERIODOS
# Período de análisis: desde START_DATE hasta AN_DATE
analysis_data = all_tickers_data.loc[START_DATE:AN_DATE]
tickers_data = analysis_data  # Datos para entrenamiento/análisis

# Período de validación: desde AN_DATE hasta END_DATE
validation_data = all_tickers_data.loc[AN_DATE:END_DATE]  # Datos para validación

print(f"✅ Datos descargados:")
print(f"   📊 Total: {all_tickers_data.shape} (desde {START_DATE} hasta {END_DATE})")
print(f"   📊 Período de análisis: {tickers_data.shape} (desde {START_DATE} hasta {AN_DATE})")
print(f"   📊 Período de validación: {validation_data.shape} (desde {AN_DATE} hasta {END_DATE})")

[*********************100%***********************]  503 of 503 completed

1 Failed download:
['EA']: Timeout('Failed to perform, curl: (28) Operation timed out after 10006 milliseconds with 0 bytes received. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')

✅ Datos descargados:
   📊 Total: (131, 502) (desde 2025-04-01 hasta 2025-10-08)
   📊 Período de análisis: (85, 502) (desde 2025-04-01 hasta 2025-08-01)
   📊 Período de validación: (47, 502) (desde 2025-08-01 hasta 2025-10-08)

In [7]:
## Datos S&P500
# Descargar SPY para benchmark
SPY_data = yf.download('SPY', start=START_DATE, end=END_DATE, auto_adjust=True)['Close']

# Verificar si es Serie o DataFrame y convertir apropiadamente
if isinstance(SPY_data, pd.Series):
    SPY = SPY_data.to_frame(name='SPY')
else:
    # Si ya es DataFrame, asegurarse que la columna se llame 'SPY'
    SPY = SPY_data.to_frame() if len(SPY_data.shape) == 1 else SPY_data
    if 'SPY' not in SPY.columns:
        SPY.columns = ['SPY']

# Dividir en períodos
SPY_analysis = SPY.loc[START_DATE:AN_DATE]
SPY_validation = SPY.loc[AN_DATE:END_DATE]

print(f"✅ SPY descargado:")
print(f"   📊 SPY_analysis: {SPY_analysis.shape}")
print(f"   📊 SPY_validation: {SPY_validation.shape}")
print(f"   📋 Columnas: {SPY_analysis.columns.tolist()}")

[*********************100%***********************]  1 of 1 completed

✅ SPY descargado:
   📊 SPY_analysis: (85, 1)
   📊 SPY_validation: (47, 1)
   📋 Columnas: ['SPY']

### Datos de métricas

In [8]:
# =======================================================
# CREAR SUBCARPETA PARA VISUALIZACIONES
# =======================================================

import os

# Crear la subcarpeta para todas las visualizaciones
output_folder = 'Mapper_final'
os.makedirs(output_folder, exist_ok=True)
print(f"📁 Subcarpeta creada: {output_folder}/")
print(f"🌐 Todas las visualizaciones HTML se guardarán en esta carpeta")

📁 Subcarpeta creada: Mapper_final/
🌐 Todas las visualizaciones HTML se guardarán en esta carpeta

In [9]:
# Sacamos métricas de cada ticker

financial_metrics = {}
print("\n🔄 Calculando métricas financieras...")
for ticker in tickers_data.columns:
    try:
        prices = tickers_data[ticker].dropna()
        returns = prices.pct_change().dropna()
        
        # Métricas básicas
        total_return = (prices.iloc[-1] / prices.iloc[0]) - 1
        volatility = returns.std() * np.sqrt(252)  # Anualizada
        sharpe = (returns.mean() * 252) / (returns.std() * np.sqrt(252)) if returns.std() > 0 else 0
        
        # Métricas de riesgo
        max_drawdown = ((prices / prices.cummax()) - 1).min()
        var_95 = returns.quantile(0.05)  # Value at Risk 95%
        skewness = returns.skew()
        kurtosis = returns.kurtosis()
        
        # Métricas de tendencia
        returns_positive_ratio = (returns > 0).mean()
        trend_slope = np.polyfit(range(len(prices)), prices.values, 1)[0]
        
        financial_metrics[ticker] = {
            'total_return': total_return,
            'volatility': volatility,
            'sharpe_ratio': sharpe,
            'max_drawdown': max_drawdown,
            'var_95': var_95,
            'skewness': skewness,
            'kurtosis': kurtosis,
            'positive_ratio': returns_positive_ratio,
            'trend_slope': trend_slope / prices.iloc[0]  # Normalizado
        }
    except Exception as e:
        print(f"❌ Error procesando {ticker}: {e}")

# Convertir a DataFrame
metrics_df = pd.DataFrame(financial_metrics).T

# Normalizar datos
scaler = StandardScaler()
metrics_scaled = scaler.fit_transform(metrics_df.fillna(0))# Datos normalizados que ya tenemos

# Preparar datos para KeplerMapper (usar métricas financieras)

ticker_names = metrics_df.index.tolist()


print(f"📊 Datos preparados: {metrics_scaled.shape[0]} tickers, {metrics_scaled.shape[1]} métricas")

🔄 Calculando métricas financieras...
📊 Datos preparados: 502 tickers, 9 métricas

In [10]:
metrics_df

,total_return,volatility,sharpe_ratio,max_drawdown,var_95,skewness,kurtosis,positive_ratio,trend_slope
A,-0.002727,0.391876,0.172752,-0.143978,-0.041324,0.050451,2.178605,0.523810,0.001788
AAPL,-0.092050,0.438495,-0.448208,-0.229890,-0.038698,1.487230,12.495893,0.535714,0.000568
ABBV,-0.036574,0.312671,-0.200549,-0.167438,-0.031001,-1.116517,2.402987,0.547619,0.000490
ABNB,0.056445,0.425379,0.592635,-0.139332,-0.034630,1.515823,10.745959,0.523810,0.002538
ABT,-0.024576,0.254078,-0.165413,-0.123327,-0.019748,-1.978507,10.320301,0.559524,0.000124
...,...,...,...,...,...,...,...,...,...
XYZ,0.336040,0.634249,1.697565,-0.218771,-0.051021,-1.201008,9.420311,0.642857,0.005643
YUM,-0.080839,0.241945,-0.922773,-0.138813,-0.019506,-1.765971,9.879517,0.488095,-0.000043
ZBH,-0.191466,0.314612,-1.863122,-0.199272,-0.023120,-2.313721,12.537985,0.535714,-0.001169
ZBRA,0.184301,0.555862,1.192548,-0.257433,-0.030912,-0.421844,10.661268,0.535714,0.004673
ZTS,-0.083616,0.303880,-0.711145,-0.141060,-0.033984,-0.045217,1.538775,0.547619,0.000048

In [11]:
metrics_scaled

array([[-0.31537539,  0.09666923, -0.22014885, ..., -0.93764187,
        -0.04988756, -0.06938036],
       [-0.72432649,  0.44366474, -0.68117995, ...,  1.28207941,
         0.16979274, -0.48179868],
       [-0.47034077, -0.49286026, -0.4973062 , ..., -0.88936707,
         0.38947303, -0.50817704],
       ...,
       [-1.17948505, -0.47841377, -1.73168203, ...,  1.29113533,
         0.16979274, -1.06909307],
       [ 0.54089725,  1.31723769,  0.53699752, ...,  0.88736746,
         0.16979274,  0.90591667],
       [-0.68571131, -0.5582914 , -0.87639734, ..., -1.07529872,
         0.38947303, -0.65764549]], shape=(502, 9))

## Creación de mappers

### Mappers con datos completos

In [12]:
# Escalamos
data = StandardScaler().fit_transform(tickers_data.T)

# Inicializamos Mapper
mapper = km.KeplerMapper(verbose=1)  # verbose=1 para ver debug info
# Proyección (lens): PCA a 2D
lens = mapper.fit_transform(data, projection=PCA(n_components=2))

# Construcción del grafo con KMeans
graph_hist_1 = mapper.map(
    lens, 
    data, 
    clusterer=KMeans(n_clusters=3, random_state=0),  # ✅ KMeans más confiable
    cover=km.Cover(n_cubes=10, perc_overlap=0.5)
)

print(f"✅ Nodos encontrados: {len(graph_hist_1['nodes'])}")
print(f"✅ Aristas encontradas: {len(graph_hist_1['links'])}")

# Visualización interactiva
mapper.visualize(graph_hist_1, 
                 title="Mapper de series de tiempo",
                 custom_tooltips=np.array(ticker_names),  # Mostrar nombres de tickers
                 path_html="Mapper_final/mapper_output.html")

KeplerMapper(verbose=1)
..Composing projection pipeline of length 1:
	Projections: PCA(n_components=2)
	Distance matrices: False
	Scalers: MinMaxScaler()
..Projecting on data shaped (502, 85)

..Projecting data using:
	PCA(n_components=2)


..Scaling with: MinMaxScaler()

Mapping on data shaped (502, 85) using lens shaped (502, 2)

Creating 100 hypercubes.

Created 76 edges and 33 nodes in 0:00:01.461748.
✅ Nodos encontrados: 33
✅ Aristas encontradas: 26
Wrote visualization to: Mapper_final/mapper_output.html

'<!DOCTYPE html>\n<html>\n\n<head>\n  <meta charset="utf-8">\n  <meta name="generator" content="KeplerMapper">\n  <title>Mapper de series de tiempo | KeplerMapper</title>\n\n  <link rel="icon" type="image/png" href="http://i.imgur.com/axOG6GJ.jpg" />\n\n  <link href=\'https://fonts.googleapis.com/css?family=Roboto+Mono:700,300\' rel=\'stylesheet\' type=\'text/css\'>\n  <style>* {\n  margin: 0;\n  padding: 0;\n}\n\nhtml, body {\n  height: 100%;\n}\n\nbody {\n  font-family: "Roboto Mono", "Helvetica", sans-serif;\n  font-size: 14px;\n}\n\n#logo {\n  width:  85px;\n  height: 85px;\n}\n\n#display {\n  color: #95A5A6;\n  background: #212121;\n}\n\n#header {\n  background: #111111;\n}\n\n#print {\n  color: #000;\n  background: #FFF;\n}\n\nh1 {\n  font-size: 21px;\n  font-weight: 300;\n  font-weight: 300;\n}\n\nh2 {\n  font-size: 18px;\n  padding-bottom: 20px;\n  font-weight: 300;\n}\n\nh3 {\n  font-size: 14px;\n  font-weight: 700;\n  text-transform: uppercase;\n}\n\nh4 {\n  font-size: 13px;\n  font-weight: 700;\n  text-transform: uppercase;\n  padding-bottom:0px;\n}\n\n\n#meta_content h3 {\n  float: left;\n  padding-right: 8px;\n}\n\np, #tooltip_content h3, ol, ul, table {\n  padding-bottom: 10px;\n}\n\nol, ul {\n  padding-left: 20px;\n}\n\nol b {\n  display: block;\n}\n\na {\n  color: #16a085;\n  text-decoration: none;\n}\n\n.pane {\n  position: relative;\n}\n\n.pane-left {\n  float: left;\n}\n\n.pane-right {\n  float: right;\n}\n\na:hover {\n  color: #2ecc71;\n}\n\n.banner {\n  /* height: 35px; */\n  padding: 10px 0px;\n}\n\n\n#print #header {\n  background: #FFF;\n}\n\n\n#canvas {\n  width: 100%;\n}\n\n#svg {\n  position: absolute;\n}\n\n#toolbar {\n  padding-top: 5px;\n  margin-bottom: 5px;\n  width: 100%;\n}\n\n#display #toolbar {\n}\n\n#display .banner {\n  border-top: 1px solid #000;\n}\n\n.inline-block {\n  display: inline-block;\n}\n\n.tool_item {\n  padding-left: 10px;\n  padding-right: 10px;\n}\n\n.pane_content {\n  width: 300px;\n  height:100%;\n  padding: 20px;\n  overflow: auto;\n  display: none;\n}\n\n.pane {\n  z-index: 1;\n}\n\n#display .pane_content {\n  background: #191919;\n}\n\n#print .pane_content{\n  background: #FFF;\n}\n\n#meta_content::-webkit-scrollbar, #tooltip_content::-webkit-scrollbar {\n  width: 1em;\n}\n\n#meta_content::-webkit-scrollbar-track, #tooltip_content::-webkit-scrollbar-track {\n  -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);\n}\n\n#meta_content::-webkit-scrollbar-thumb, #tooltip_content::-webkit-scrollbar-thumb {\n  background-color: darkgrey;\n  outline: 1px solid slategrey;\n}\n\n.histogram {\n  display: block;\n  height: 100px;\n  padding-top: 50px;\n  clear: both;\n}\n\n#display .histogram {\n  opacity: 0.68;\n}\n\n.bin {\n  width: 10%;\n  float: left;\n}\n\n.bin div {\n  font-size: 10px;\n  display: block;\n  width: 35px;\n  margin-top: -30px;\n  text-align: right;\n  margin-left: -3px;\n  -webkit-transform: rotate(-90deg);\n  -moz-transform: rotate(-90deg);\n  -ms-transform: rotate(-90deg);\n  -o-transform: rotate(-90deg);\n}\n\n.histogram:hover {\n  opacity: 1.;\n}\n\n#display .circle {\n  stroke-opacity: 0.18;\n  stroke-width: 7px;\n  stroke: #000;\n}\n\n#print .circle {\n  stroke-opacity: 1;\n  stroke-width: 2px;\n  stroke: #000;\n  stroke-linecap: round;\n}\n\n#print .link {\n  stroke: #000;\n}\n\n#display .link {\n  stroke: rgba(160, 160, 160, 0.5);\n}\n\ntable {\n  border-collapse: collapse;\n  display: table;\n  width: 100%;\n  margin-bottom: 20px;\n}\n\ntd, th {\n  padding: 5px;\n  text-align: left;\n}\n\n#display th {\n  background: #212121\n}\n\ntd {\n  border-bottom: 1px solid #111;\n}\n\n.highlight {\n  filter: url(#drop-shadow-pulse);\n}\n\n.control-row {\n  padding: 5px 0px;\n}\n\n.btn {\n  display: inline-block;\n  padding: 0.35em 1.2em;\n  border: 0.1em solid #FFFFFF;\n  margin: 0 0.3em 0.3em 0;\n  border-radius: 0.12em;\n  box-sizing: border-box;\n  text-decoration: none;\n  background-color: transparent;\n  font-weight: 300;\n  color: #FFFFFF;\n  text-align: center;\n  transition: all 0.2s;\n}\n\n.btn:hover {\n  color: #000000;\n  background-color: #FFFFFF;\n}\n\n.btn:disabled {\n  color: #FFFFFF;\n  opacity: .35;\n}\n\n#print .btn {\n  color: #000;\n  border-color: #000\n}\n\n#print .btn:hover {\n  color: #FFFFFF;\n  background-color: #000000\n}\n\n#print .btn:disabled {}\n\n#toolbar .btn {\n  padding: 0 1.2em;\n}\n\nlabel {\n  display: inline-block;\n  margin-bottom: .5rem;\n}\n\n#config-file-loader {\n  margin-bottom: .5em;\n}\n\n.btn:not(:disabled):not(.disabled) {\n    cursor: pointer;\n}\n\n.wrap {\n  display: flex;\n}\n\n.wrap-header div:last-child {\n  margin-left: auto;\n}\n\n.wrap-end {\n  justify-content: flex-end;\n}\n\n.wrap-logo {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}\n\n.wrap-logo .logo {\n  margin: auto;\n}\n\n.wrap-header {\n  /* padding: 5px 10px; */\n  padding: 5px 5px 5px 10px;\n  justify-content: space-between;\n}\n\n#display .wrap-header {\n  box-shadow: 0px 0px 4px #000;\n}\n\n.toolbar-container {\n  margin-left: -10px;\n}\n</style>\n\n</head>\n\n<body id="display">\n\n  <!-- Variables used later -->\n  <script>\n    const graph = {"links": [{"source": 0, "target": 5, "width": 1}, {"source": 0, "target": 17, "width": 1}, {"source": 0, "target": 18, "width": 1}, {"source": 1, "target": 3, "width": 1}, {"source": 1, "target": 15, "width": 1}, {"source": 1, "target": 20, "width": 1}, {"source": 2, "target": 4, "width": 1}, {"source": 3, "target": 7, "width": 1}, {"source": 3, "target": 15, "width": 1}, {"source": 3, "target": 19, "width": 1}, {"source": 3, "target": 20, "width": 1}, {"source": 3, "target": 21, "width": 1}, {"source": 3, "target": 22, "width": 1}, {"source": 4, "target": 6, "width": 1}, {"source": 4, "target": 8, "width": 1}, {"source": 5, "target": 7, "width": 1}, {"source": 5, "target": 8, "width": 1}, {"source": 5, "target": 17, "width": 1}, {"source": 5, "target": 18, "width": 1}, {"source": 5, "target": 23, "width": 1}, {"source": 6, "target": 9, "width": 1}, {"source": 6, "target": 11, "width": 1}, {"source": 7, "target": 10, "width": 1}, {"source": 7, "target": 18, "width": 1}, {"source": 7, "target": 19, "width": 1}, {"source": 7, "target": 20, "width": 1}, {"source": 7, "target": 21, "width": 1}, {"source": 7, "target": 22, "width": 1}, {"source": 7, "target": 23, "width": 1}, {"source": 7, "target": 24, "width": 1}, {"source": 7, "target": 25, "width": 1}, {"source": 7, "target": 26, "width": 1}, {"source": 8, "target": 11, "width": 1}, {"source": 8, "target": 18, "width": 1}, {"source": 8, "target": 23, "width": 1}, {"source": 8, "target": 26, "width": 1}, {"source": 10, "target": 12, "width": 1}, {"source": 10, "target": 14, "width": 1}, {"source": 10, "target": 21, "width": 1}, {"source": 10, "target": 22, "width": 1}, {"source": 10, "target": 23, "width": 1}, {"source": 10, "target": 24, "width": 1}, {"source": 10, "target": 25, "width": 1}, {"source": 10, "target": 26, "width": 1}, {"source": 10, "target": 28, "width": 1}, {"source": 10, "target": 29, "width": 1}, {"source": 11, "target": 13, "width": 1}, {"source": 11, "target": 23, "width": 1}, {"source": 11, "target": 26, "width": 1}, {"source": 11, "target": 27, "width": 1}, {"source": 12, "target": 25, "width": 1}, {"source": 12, "target": 28, "width": 1}, {"source": 13, "target": 26, "width": 1}, {"source": 13, "target": 27, "width": 1}, {"source": 14, "target": 24, "width": 1}, {"source": 14, "target": 29, "width": 1}, {"source": 15, "target": 20, "width": 1}, {"source": 16, "target": 19, "width": 1}, {"source": 16, "target": 30, "width": 1}, {"source": 17, "target": 18, "width": 1}, {"source": 18, "target": 23, "width": 1}, {"source": 19, "target": 22, "width": 1}, {"source": 19, "target": 30, "width": 1}, {"source": 19, "target": 31, "width": 1}, {"source": 19, "target": 32, "width": 1}, {"source": 20, "target": 21, "width": 1}, {"source": 21, "target": 24, "width": 1}, {"source": 21, "target": 25, "width": 1}, {"source": 22, "target": 25, "width": 1}, {"source": 22, "target": 31, "width": 1}, {"source": 22, "target": 32, "width": 1}, {"source": 23, "target": 24, "width": 1}, {"source": 23, "target": 26, "width": 1}, {"source": 24, "target": 29, "width": 1}, {"source": 25, "target": 28, "width": 1}, {"source": 26, "target": 27, "width": 1}], "nodes": [{"color": [[0.39920159680638717]], "id": "", "name": "cube0_cluster0", "size": 1, "tooltip": {"cluster_stats": {"above": [], "below": [], "size": 1}, "custom_tooltips": ["GEV"], "dist_label": "Member", "histogram": [[{"color": "rgb(70, 18, 100)", "height": 0.0, "perc": 0.0}, {"color": "rgb(68, 51, 125)", "height": 0.0, "perc": 0.0}, {"color": "rgb(58, 80, 138)", "height": 0.0, "perc": 0.0}, {"color": "rgb(46, 107, 141)", "height": 100.0, "perc": 100.0}, {"color": "rgb(36, 131, 141)", "height": 0.0, "perc": 0.0}, {"color": "rgb(33, 155, 136)", "height": 0.0, "perc": 0.0}, {"color": "rgb(51, 178, 121)", "height": 0.0, "perc": 0.0}, {"color": "rgb(94, 199, 96)", "height": 0.0, "perc": 0.0}, {"color": "rgb(155, 215, 59)", "height": 0.0, "perc": 0.0}, {"color": "rgb(220, 226, 37)", "height": 0.0, "perc": 0.0}]], "node_id": "cube0_cluster0", "projection_stats": []}, "type": "circle"}, {"color": [[0.5169660678642715]], "id": "", "name": "cube0_cluster1", "size": 2, "tooltip": {"cluster_stats": {"above": [], "below": [], "size": 3}, "custom_tooltips": ["AXON", "KLAC", "URI"], "dist_label": "Member", "histogram": [[{"color": "rgb(70, 18, 100)", "height": 100.0, "perc": 33.3}, {"color": "rgb(68, 51, 125)", "height": 0.0, "perc": 0.0}, {"color": "rgb(58, 80, 138)", "height": 0.0, "perc": 0.0}, {"color": "rgb(46, 107, 141)", "height": 0.0, "perc": 0.0}, {"color": "rgb(36, 131, 141)", "height": 0.0, "perc": 0.0}, {"color": "rgb(33, 155, 136)", "height": 100.0, "perc": 33.3}, {"color": "rgb(51, 178, 121)", "height": 0.0, "perc": 0.0}, {"color": "rgb(94, 199, 96)", "height": 0.0, "perc": 0.0}, {"color": "rgb(155, 215, 59)", "height": 0.0, "perc": 0.0}, {"color": "rgb(220, 226, 37)", "height": 100.0, "perc": 33.3}]], "node_id": "cube0_cluster1", "projection_stats": []}, "type": "circle"}, {"color": [[0.20359281437125748]], "id": "", "name": "cube0_cluster2", "size": 1, "tooltip": {"cluster_stats": {"above": [], "below": [], "size": 1}, "custom_tooltips": ["COIN"], "dist_label": "Member", "histogram": [[{"color": "rgb(70, 18, 100)", "height": 0.0, "perc": 0.0}, {"color": "rgb(68, 51, 125)", "height": 0.0, "perc": 0.0}, {"color": "rgb(58, 80, 138)", "height": 100.0, "perc": 100.0}, {"color": "rgb(46, 107, 141)", "height": 0.0, "perc": 0.0}, {"color": "rgb(36, 131, 141)", "height": 0.0, "perc": 0.0}, {"color": "rgb(33, 155, 136)", "height": 0.0, "perc": 0.0}, {"color": "rgb(51, 178, 121)", "height": 0.0, "perc": 0.0}, {"color": "rgb(94, 199, 96)", "height": 0.0, "perc": 0.0}, {"color": "rgb(155, 215, 59)", "height": 0.0, "perc": 0.0}, {"color": "rgb(220, 226, 37)", "height": 0.0, "perc": 0.0}]], "node_id": "cube0_cluster2", "projection_stats": []}, "type": "circle"}, {"color": [[0.5225548902195608]], "id": "", "name": "cube1_cluster0", "size": 3, "tooltip": {"cluster_stats": {"above": [], "below": [], "size": 10}, "custom_tooltips": ["AXON", "BLK", "GS", "INTU", "KLAC", "META", "MPWR", "NOW", "PH", "URI"], "dist_label": "Member", "histogram": [[{"color": "rgb(70, 18, 100)", "height": 33.0, "perc": 10.0}, {"color": "rgb(68, 51, 125)", "height": 33.0, "perc": 10.0}, {"color": "rgb(58, 80, 138)", "height": 0.0, "perc": 0.0}, {"color": "rgb(46, 107, 141)", "height": 0.0, "perc": 0.0}, {"color": "rgb(36, 131, 141)", "height": 67.0, "perc": 20.0}, {"color": "rgb(33, 155, 136)", "height": 33.0, "perc": 10.0}, {"color": "rgb(51, 178, 121)", "height": 100.0, "perc": 30.0}, {"color": "rgb(94, 199, 96)", "height": 33.0, "perc": 10.0}, {"color": "rgb(155, 215, 59)", "height": 0.0, "perc": 0.0}, {"color": "rgb(220, 226, 37)", "height": 33.0, "perc": 10.0}]], "node_id": "cube1_cluster0", "projection_stats": []}, "type": "circle"}, {"color": [[0.4910978043912175]], "id": "", "name": "cube1_cluster1", "size": 4, "tooltip": {"cluster_stats": {"above": [], "below": [], "size": 25}, "custom_tooltips": ["ADI", "AMD", "AVGO", "BA", "CEG", "COIN", "DASH", "DDOG", "DELL", "GE", "HOOD", "HWM", "JBL", "JPM", "MU", "NRG", "NVDA", "ORCL", "PLTR", "RCL", "RL", "STX", "TEL", "TXN", "VST"], "dist_label": "Member", "histogram": [[{"color": "rgb(70, 18, 100)", "height": 100.0, "perc": 16.0}, {"color": "rgb(68, 51, 125)", "height": 25.0, "perc": 4.0}, {"color": "rgb(58, 80, 138)", "height": 100.0, "perc": 16.0}, {"color": "rgb(46, 107, 141)", "height": 25.0, "perc": 4.0}, {"color": "rgb(36, 131, 141)", "height": 50.0, "perc": 8.0}, {"color": "rgb(33, 155, 136)", "height": 50.0, "perc": 8.0}, {"color": "rgb(51, 178, 121)", "height": 75.0, "perc": 12.0}, {"color": "rgb(94, 199, 96)", "height": 100.0, "perc": 16.0}, {"color": "rgb(155, 215, 59)", "height": 50.0, "perc": 8.0}, {"color": "rgb(220, 226, 37)", "height": 50.0, "perc": 8.0}]], "node_id": "cube1_cluster1", "projection_stats": []}, "type": "circle"}, {"color": [[0.5722305389221556]], "id": "", "name": "cube1_cluster2", "size": 3, "tooltip": {"cluster_stats": {"above": [], "below": [], "size": 16}, "custom_tooltips": ["APP", "CAT", "CRWD", "EME", "ETN", "GEV", "HUBB", "IDXX", "MSFT", "PWR", "ROK", "SNPS", "TSLA", "TT", "ULTA", "ZBRA"], "dist_label": "Member", "histogram": [[{"color": "rgb(70, 18, 100)", "height": 33.0, "perc": 6.2}, {"color": "rgb(68, 51, 125)", "height": 33.0, "perc": 6.2}, {"color": "rgb(58, 80, 138)", "height": 33.0, "perc": 6.2}, {"color": "rgb(46, 107, 141)", "height": 100.0, "perc": 18.8}, {"color": "rgb(36, 131, 141)", "height": 67.0, "perc": 12.5}, {"color": "rgb(33, 155, 136)", "height": 0.0, "perc": 0.0}, {"color": "rgb(51, 178, 121)", "height": 33.0, "perc": 6.2}, {"color": "rgb(94, 199, 96)", "height": 67.0, "perc": 12.5}, {"color": "rgb(155, 215, 59)", "height": 100.0, "perc": 18.8}, {"color": "rgb(220, 226, 37)", "height": 67.0, "perc": 12.5}]], "node_id": "cube1_cluster2", "projection_stats": []}, "type": "circle"}, {"color": [[0.5050606183132127]], "id": "", "name": "cube2_cluster0", "size": 6, "tooltip": {"cluster_stats": {"above": [], "below": [], "size": 311}, "custom_tooltips": ["A", "ABNB", "ABT", "ACGL", "ADM", "AEE", "AEP", "AES", "AFL", "AIG", "AKAM", "ALB", "ALLE", "AMCR", "AMD", "ANET", "AOS", "APA", "APH", "APO", "APTV", "ARE", "ATO", "AWK", "BAC", "BALL", "BAX", "BBY", "BEN", "BF-B", "BG", "BIIB", "BK", "BKR", "BLDR", "BMY", "BRO", "BSX", "BX", "BXP", "C", "CAG", "CAH", "CARR", "CBRE", "CCI", "CCL", "CF", "CFG", "CHD", "CHRW", "CINF", "CL", "CLX", "CMCSA", "CMG", "CMS", "CNC", "CNP", "COO", "COP", "CPB", "CPRT", "CPT", "CRL", "CSCO", "CSGP", "CSX", "CTRA", "CTSH", "CTVA", "CVS", "CVX", "D", "DAL", "DAY", "DD", "DDOG", "DECK", "DELL", "DG", "DHI", "DIS", "DLTR", "DOC", "DOW", "DTE", "DUK", "DVA", "DVN", "DXCM", "EBAY", "ED", "EIX", "EL", "EMN", "EMR", "EOG", "EQR", "EQT", "ES", "ETR", "EVRG", "EW", "EXC", "EXE", "EXPD", "EXR", "F", "FANG", "FAST", "FCX", "FE", "FIS", "FITB", "FOX", "FOXA", "FRT", "FSLR", "FTNT", "FTV", "GEHC", "GEN", "GILD", "GIS", "GL", "GLW", "GM", "GNRC", "GPC", "GPN", "HAL", "HAS", "HBAN", "HIG", "HOLX", "HOOD", "HPE", "HPQ", "HRL", "HSIC", "HST", "HWM", "IBKR", "IFF", "INCY", "INTC", "INVH", "IP", "IPG", "IQV", "IR", "IRM", "IVZ", "J", "JBHT", "JCI", "JNJ", "K", "KDP", "KEY", "KEYS", "KHC", "KIM", "KKR", "KMB", "KMI", "KMX", "KO", "KR", "KVUE", "L", "LDOS", "LEN", "LKQ", "LNT", "LRCX", "LUV", "LVS", "LW", "LYB", "LYV", "MAA", "MAS", "MCHP", "MDLZ", "MDT", "MET", "MGM", "MHK", "MKC", "MMM", "MNST", "MO", "MOS", "MPC", "MRK", "MRNA", "MS", "MTCH", "MU", "NCLH", "NDAQ", "NEE", "NEM", "NI", "NKE", "NRG", "NTAP", "NTRS", "NUE", "NVDA", "NWS", "NWSA", "O", "ODFL", "OKE", "OMC", "ON", "ORLY", "OTIS", "OXY", "PAYX", "PCAR", "PCG", "PEG", "PEP", "PFE", "PFG", "PG", "PHM", "PLD", "PLTR", "PNR", "PNW", "PPG", "PPL", "PRU", "PSKY", "PSX", "PYPL", "QCOM", "REG", "RF", "RJF", "ROL", "ROST", "RTX", "RVTY", "SBUX", "SCHW", "SJM", "SLB", "SMCI", "SO", "SOLV", "SPG", "SRE", "STLD", "STT", "STX", "SW", "SWK", "SWKS", "SYF", "SYY", "T", "TAP", "TECH", "TEL", "TER", "TFC", "TGT", "TJX", "TPR", "TRMB", "TROW", "TSCO", "TSN", "TTD", "TXT", "UAL", "UBER", "UDR", "UPS", "USB", "VICI", "VLO", "VLTO", "VST", "VTR", "VTRS", "VZ", "WBD", "WDC", "WEC", "WELL", "WFC", "WMB", "WMT", "WRB", "WSM", "WY", "WYNN", "XEL", "XOM", "XYL", "XYZ", "YUM", "ZBH", "ZTS"], "dist_label": "Member", "histogram": [[{"color": "rgb(70, 18, 100)", "height": 69.0, "perc": 7.7}, {"color": "rgb(68, 51, 125)", "height": 100.0, "perc": 11.3}, {"color": "rgb(58, 80, 138)", "height": 94.0, "perc": 10.6}, {"color": "rgb(46, 107, 141)", "height": 89.0, "perc": 10.0}, {"color": "rgb(36, 131, 141)", "height": 86.0, "perc": 9.6}, {"color": "rgb(33, 155, 136)", "height": 91.0, "perc": 10.3}, {"color": "rgb(51, 178, 121)", "height": 94.0, "perc": 10.6}, {"color": "rgb(94, 199, 96)", "height": 86.0, "perc": 9.6}, {"color": "rgb(155, 215, 59)", "height": 91.0, "perc": 10.3}, {"color": "rgb(220, 226, 37)", "height": 89.0, "perc": 10.0}]], "node_id": "cube2_cluster0", "projection_stats": []}, "type": "circle"}, {"color": [[0.5760058829709002]], "id": "", "name": "cube2_cluster1", "size": 4, "tooltip": {"cluster_stats": {"above": [], "below": [], "size": 38}, "custom_tooltips": ["AMP", "BLK", "CRWD", "DE", "DPZ", "EME", "EQIX", "FDS", "GS", "GWW", "IDXX", "INTU", "ISRG", "IT", "LII", "LIN", "LMT", "MA", "MCK", "MCO", "META", "MLM", "MPWR", "MSCI", "MSFT", "MSI", "NOC", "NOW", "PH", "ROP", "SNPS", "SPGI", "TDY", "TMO", "TT", "TYL", "ULTA", "VRTX"], "dist_label": "Member", "histogram": [[{"color": "rgb(70, 18, 100)", "height": 13.0, "perc": 2.6}, {"color": "rgb(68, 51, 125)", "height": 13.0, "perc": 2.6}, {"color": "rgb(58, 80, 138)", "height": 38.0, "perc": 7.9}, {"color": "rgb(46, 107, 141)", "height": 38.0, "perc": 7.9}, {"color": "rgb(36, 131, 141)", "height": 75.0, "perc": 15.8}, {"color": "rgb(33, 155, 136)", "height": 75.0, "perc": 15.8}, {"color": "rgb(51, 178, 121)", "height": 100.0, "perc": 21.1}, {"color": "rgb(94, 199, 96)", "height": 25.0, "perc": 5.3}, {"color": "rgb(155, 215, 59)", "height": 63.0, "perc": 13.2}, {"color": "rgb(220, 226, 37)", "height": 38.0, "perc": 7.9}]], "node_id": "cube2_cluster1", "projection_stats": []}, "type": "circle"}, {"color": [[0.46736829371559907]], "id": "", "name": "cube2_cluster2", "size": 5, "tooltip": {"cluster_stats": {"above": [], "below": [], "size": 132}, "custom_tooltips": ["AAPL", "ABBV", "ACN", "ADBE", "ADI", "ADP", "ADSK", "AIZ", "AJG", "ALGN", "ALL", "AMAT", "AME", "AMGN", "AMT", "AMZN", "AON", "APD", "APP", "AVB", "AVGO", "AVY", "AXP", "BA", "BDX", "BR", "CAT", "CB", "CBOE", "CDNS", "CDW", "CEG", "CHTR", "CI", "CME", "CMI", "COF", "COR", "CPAY", "CRM", "CTAS", "DASH", "DGX", "DHR", "DLR", "DOV", "DRI", "ECL", "EFX", "EG", "EPAM", "ESS", "ETN", "EXPE", "FDX", "FFIV", "FI", "GD", "GDDY", "GE", "GOOG", "GOOGL", "GRMN", "HCA", "HD", "HII", "HLT", "HON", "HSY", "HUBB", "HUM", "IBM", "ICE", "IEX", "ITW", "JBL", "JKHY", "JPM", "LH", "LHX", "LOW", "LULU", "MAR", "MCD", "MMC", "MTB", "NDSN", "NSC", "NXPI", "ORCL", "PANW", "PAYC", "PGR", "PKG", "PM", "PNC", "PODD", "POOL", "PSA", "PTC", "PWR", "RCL", "RL", "RMD", "ROK", "RSG", "SBAC", "SHW", "SNA", "STE", "STZ", "SYK", "TKO", "TMUS", "TRGP", "TRV", "TSLA", "TTWO", "TXN", "UHS", "UNP", "V", "VMC", "VRSK", "VRSN", "WAB", "WAT", "WDAY", "WM", "WST", "WTW", "ZBRA"], "dist_label": "Member", "histogram": [[{"color": "rgb(70, 18, 100)", "height": 100.0, "perc": 18.2}, {"color": "rgb(68, 51, 125)", "height": 50.0, "perc": 9.1}, {"color": "rgb(58, 80, 138)", "height": 50.0, "perc": 9.1}, {"color": "rgb(46, 107, 141)", "height": 50.0, "perc": 9.1}, {"color": "rgb(36, 131, 141)", "height": 58.0, "perc": 10.6}, {"color": "rgb(33, 155, 136)", "height": 42.0, "perc": 7.6}, {"color": "rgb(51, 178, 121)", "height": 21.0, "perc": 3.8}, {"color": "rgb(94, 199, 96)", "height":

### Mappers con métricas

In [13]:
# 1. Crear el mapper
mapper = km.KeplerMapper(verbose=1)

KeplerMapper(verbose=1)

In [14]:
# Configuración 1: Proyección por Sharpe
projected_data_sharpe = mapper.fit_transform(metrics_scaled, projection=[2])  # Sharpe ratio (índice 2)
covering = km.Cover(n_cubes=6, perc_overlap=0.5)
G = mapper.map(projected_data_sharpe, metrics_scaled, 
               clusterer=sklearn.cluster.KMeans(n_clusters=2),
               cover=covering)

mapper.visualize(G, 
                title='Mapper: Agrupación por Sharpe',
                color_values=metrics_df['sharpe_ratio'].values,
                color_function_name='Sharpe Ratio',
                node_color_function=np.array(['average','std','sum','max','min']),
                custom_tooltips=np.array(ticker_names),  # Mostrar nombres de tickers
                path_html='Mapper_final/mapper_principal_sharpe.html')  # Guardado en subcarpeta

print(f"Nodos: {len(G['nodes'])}, Aristas: {len(G['links'])}")

..Composing projection pipeline of length 1:
	Projections: [2]
	Distance matrices: False
	Scalers: MinMaxScaler()
..Projecting on data shaped (502, 9)

..Projecting data using: [2]

..Scaling with: MinMaxScaler()

Mapping on data shaped (502, 9) using lens shaped (502, 1)

Creating 6 hypercubes.

Created 15 edges and 12 nodes in 0:00:00.024320.
Wrote visualization to: Mapper_final/mapper_principal_sharpe.html
Nodos: 12, Aristas: 10

In [15]:
# Configuración 2: Proyección por Volatilidad

projected_data_vol = mapper.fit_transform(metrics_scaled, projection=[1])  # Volatilidad (índice 1)
covering_vol = km.Cover(n_cubes=8, perc_overlap=0.4)
G_vol = mapper.map(projected_data_vol, metrics_scaled, 
                   clusterer=sklearn.cluster.KMeans(n_clusters=3),
                   cover=covering_vol)

mapper.visualize(G_vol, 
                title='Mapper: Agrupación por Volatilidad',
                color_values=metrics_df['volatility'].values,
                color_function_name='Volatilidad',
                node_color_function=np.array(['average','max']),
                custom_tooltips=np.array(ticker_names),  # Mostrar nombres de tickers
                path_html='visualizaciones_mapper_indice/mapper_config_volatilidad.html')  # Guardado en subcarpeta

print(f"Nodos: {len(G_vol['nodes'])}, Aristas: {len(G_vol['links'])}")

..Composing projection pipeline of length 1:
	Projections: [1]
	Distance matrices: False
	Scalers: MinMaxScaler()
..Projecting on data shaped (502, 9)

..Projecting data using: [1]

..Scaling with: MinMaxScaler()

Mapping on data shaped (502, 9) using lens shaped (502, 1)

Creating 8 hypercubes.

Created 34 edges and 24 nodes in 0:00:00.030882.
Wrote visualization to: visualizaciones_mapper_indice/mapper_config_volatilidad.html
Nodos: 24, Aristas: 21

In [16]:
# Configuración 3: Proyección por Retorno Total

projected_data_ret = mapper.fit_transform(metrics_scaled, projection=[0])  # Retorno total (índice 0)
covering_ret = km.Cover(n_cubes=7, perc_overlap=0.3)
G_ret = mapper.map(projected_data_ret, metrics_scaled, 
                   clusterer=sklearn.cluster.DBSCAN(eps=0.5, min_samples=1),
                   cover=covering_ret)

mapper.visualize(G_ret, 
                title='Mapper: Agrupación por Retorno Total',
                node_color_function=np.array(['average','std']),
                custom_tooltips=np.array(ticker_names),  # Mostrar nombres de tickers
                path_html='visualizaciones_mapper_indice/mapper_config_retorno_total.html')  # Guardado en subcarpeta

print(f"Nodos: {len(G_ret['nodes'])}, Aristas: {len(G_ret['links'])}")

..Composing projection pipeline of length 1:
	Projections: [0]
	Distance matrices: False
	Scalers: MinMaxScaler()
..Projecting on data shaped (502, 9)

..Projecting data using: [0]

..Scaling with: MinMaxScaler()

Mapping on data shaped (502, 9) using lens shaped (502, 1)

Creating 7 hypercubes.

Created 209 edges and 688 nodes in 0:00:00.083433.
Wrote visualization to: visualizaciones_mapper_indice/mapper_config_retorno_total.html
Nodos: 688, Aristas: 209

In [17]:
# Configuración 4: Proyección Multi-dimensional (PCA)
projected_data_pca = mapper.fit_transform(metrics_scaled, projection='sum')  # Proyección suma
covering_pca = km.Cover(n_cubes=5, perc_overlap=0.6)
G_pca = mapper.map(projected_data_pca, metrics_scaled, 
                   clusterer=sklearn.cluster.KMeans(n_clusters=2),
                   cover=covering_pca)

mapper.visualize(G_pca, 
                title='Mapper: Proyección PCA (Suma)',
                node_color_function=np.array(['min','average']),
                custom_tooltips=np.array(ticker_names),  # Mostrar nombres de tickers
                path_html='visualizaciones_mapper_indice/mapper_config_pca_suma.html')  # Guardado en subcarpeta

..Composing projection pipeline of length 1:
	Projections: sum
	Distance matrices: False
	Scalers: MinMaxScaler()
..Projecting on data shaped (502, 9)

..Projecting data using: sum

..Scaling with: MinMaxScaler()

Mapping on data shaped (502, 9) using lens shaped (502, 1)

Creating 5 hypercubes.

Created 21 edges and 10 nodes in 0:00:00.023242.
Wrote visualization to: visualizaciones_mapper_indice/mapper_config_pca_suma.html

'<!DOCTYPE html>\n<html>\n\n<head>\n  <meta charset="utf-8">\n  <meta name="generator" content="KeplerMapper">\n  <title>Mapper: Proyección PCA (Suma) | KeplerMapper</title>\n\n  <link rel="icon" type="image/png" href="http://i.imgur.com/axOG6GJ.jpg" />\n\n  <link href=\'https://fonts.googleapis.com/css?family=Roboto+Mono:700,300\' rel=\'stylesheet\' type=\'text/css\'>\n  <style>* {\n  margin: 0;\n  padding: 0;\n}\n\nhtml, body {\n  height: 100%;\n}\n\nbody {\n  font-family: "Roboto Mono", "Helvetica", sans-serif;\n  font-size: 14px;\n}\n\n#logo {\n  width:  85px;\n  height: 85px;\n}\n\n#display {\n  color: #95A5A6;\n  background: #212121;\n}\n\n#header {\n  background: #111111;\n}\n\n#print {\n  color: #000;\n  background: #FFF;\n}\n\nh1 {\n  font-size: 21px;\n  font-weight: 300;\n  font-weight: 300;\n}\n\nh2 {\n  font-size: 18px;\n  padding-bottom: 20px;\n  font-weight: 300;\n}\n\nh3 {\n  font-size: 14px;\n  font-weight: 700;\n  text-transform: uppercase;\n}\n\nh4 {\n  font-size: 13px;\n  font-weight: 700;\n  text-transform: uppercase;\n  padding-bottom:0px;\n}\n\n\n#meta_content h3 {\n  float: left;\n  padding-right: 8px;\n}\n\np, #tooltip_content h3, ol, ul, table {\n  padding-bottom: 10px;\n}\n\nol, ul {\n  padding-left: 20px;\n}\n\nol b {\n  display: block;\n}\n\na {\n  color: #16a085;\n  text-decoration: none;\n}\n\n.pane {\n  position: relative;\n}\n\n.pane-left {\n  float: left;\n}\n\n.pane-right {\n  float: right;\n}\n\na:hover {\n  color: #2ecc71;\n}\n\n.banner {\n  /* height: 35px; */\n  padding: 10px 0px;\n}\n\n\n#print #header {\n  background: #FFF;\n}\n\n\n#canvas {\n  width: 100%;\n}\n\n#svg {\n  position: absolute;\n}\n\n#toolbar {\n  padding-top: 5px;\n  margin-bottom: 5px;\n  width: 100%;\n}\n\n#display #toolbar {\n}\n\n#display .banner {\n  border-top: 1px solid #000;\n}\n\n.inline-block {\n  display: inline-block;\n}\n\n.tool_item {\n  padding-left: 10px;\n  padding-right: 10px;\n}\n\n.pane_content {\n  width: 300px;\n  height:100%;\n  padding: 20px;\n  overflow: auto;\n  display: none;\n}\n\n.pane {\n  z-index: 1;\n}\n\n#display .pane_content {\n  background: #191919;\n}\n\n#print .pane_content{\n  background: #FFF;\n}\n\n#meta_content::-webkit-scrollbar, #tooltip_content::-webkit-scrollbar {\n  width: 1em;\n}\n\n#meta_content::-webkit-scrollbar-track, #tooltip_content::-webkit-scrollbar-track {\n  -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);\n}\n\n#meta_content::-webkit-scrollbar-thumb, #tooltip_content::-webkit-scrollbar-thumb {\n  background-color: darkgrey;\n  outline: 1px solid slategrey;\n}\n\n.histogram {\n  display: block;\n  height: 100px;\n  padding-top: 50px;\n  clear: both;\n}\n\n#display .histogram {\n  opacity: 0.68;\n}\n\n.bin {\n  width: 10%;\n  float: left;\n}\n\n.bin div {\n  font-size: 10px;\n  display: block;\n  width: 35px;\n  margin-top: -30px;\n  text-align: right;\n  margin-left: -3px;\n  -webkit-transform: rotate(-90deg);\n  -moz-transform: rotate(-90deg);\n  -ms-transform: rotate(-90deg);\n  -o-transform: rotate(-90deg);\n}\n\n.histogram:hover {\n  opacity: 1.;\n}\n\n#display .circle {\n  stroke-opacity: 0.18;\n  stroke-width: 7px;\n  stroke: #000;\n}\n\n#print .circle {\n  stroke-opacity: 1;\n  stroke-width: 2px;\n  stroke: #000;\n  stroke-linecap: round;\n}\n\n#print .link {\n  stroke: #000;\n}\n\n#display .link {\n  stroke: rgba(160, 160, 160, 0.5);\n}\n\ntable {\n  border-collapse: collapse;\n  display: table;\n  width: 100%;\n  margin-bottom: 20px;\n}\n\ntd, th {\n  padding: 5px;\n  text-align: left;\n}\n\n#display th {\n  background: #212121\n}\n\ntd {\n  border-bottom: 1px solid #111;\n}\n\n.highlight {\n  filter: url(#drop-shadow-pulse);\n}\n\n.control-row {\n  padding: 5px 0px;\n}\n\n.btn {\n  display: inline-block;\n  padding: 0.35em 1.2em;\n  border: 0.1em solid #FFFFFF;\n  margin: 0 0.3em 0.3em 0;\n  border-radius: 0.12em;\n  box-sizing: border-box;\n  text-decoration: none;\n  background-color: transparent;\n  font-weight: 300;\n  color: #FFFFFF;\n  text-align: center;\n  transition: all 0.2s;\n}\n\n.btn:hover {\n  color: #000000;\n  background-color: #FFFFFF;\n}\n\n.btn:disabled {\n  color: #FFFFFF;\n  opacity: .35;\n}\n\n#print .btn {\n  color: #000;\n  border-color: #000\n}\n\n#print .btn:hover {\n  color: #FFFFFF;\n  background-color: #000000\n}\n\n#print .btn:disabled {}\n\n#toolbar .btn {\n  padding: 0 1.2em;\n}\n\nlabel {\n  display: inline-block;\n  margin-bottom: .5rem;\n}\n\n#config-file-loader {\n  margin-bottom: .5em;\n}\n\n.btn:not(:disabled):not(.disabled) {\n    cursor: pointer;\n}\n\n.wrap {\n  display: flex;\n}\n\n.wrap-header div:last-child {\n  margin-left: auto;\n}\n\n.wrap-end {\n  justify-content: flex-end;\n}\n\n.wrap-logo {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}\n\n.wrap-logo .logo {\n  margin: auto;\n}\n\n.wrap-header {\n  /* padding: 5px 10px; */\n  padding: 5px 5px 5px 10px;\n  justify-content: space-between;\n}\n\n#display .wrap-header {\n  box-shadow: 0px 0px 4px #000;\n}\n\n.toolbar-container {\n  margin-left: -10px;\n}\n</style>\n\n</head>\n\n<body id="display">\n\n  <!-- Variables used later -->\n  <script>\n    const graph = {"links": [{"source": 0, "target": 2, "width": 1}, {"source": 0, "target": 3, "width": 1}, {"source": 0, "target": 4, "width": 1}, {"source": 1, "target": 3, "width": 1}, {"source": 1, "target": 4, "width": 1}, {"source": 2, "target": 4, "width": 1}, {"source": 2, "target": 5, "width": 1}, {"source": 2, "target": 6, "width": 1}, {"source": 3, "target": 4, "width": 1}, {"source": 3, "target": 5, "width": 1}, {"source": 3, "target": 6, "width": 1}, {"source": 3, "target": 7, "width": 1}, {"source": 4, "target": 6, "width": 1}, {"source": 5, "target": 6, "width": 1}, {"source": 5, "target": 7, "width": 1}, {"source": 5, "target": 8, "width": 1}, {"source": 5, "target": 9, "width": 1}, {"source": 6, "target": 8, "width": 1}, {"source": 6, "target": 9, "width": 1}, {"source": 7, "target": 8, "width": 1}, {"source": 7, "target": 9, "width": 1}], "nodes": [{"color": [[0.011976047904191616], [0.4753735771699844]], "id": "", "name": "cube0_cluster0", "size": 4, "tooltip": {"cluster_stats": {"above": [], "below": [], "size": 37}, "custom_tooltips": ["ACN", "AJG", "ARE", "BMY", "BRO", "CAG", "CHD", "CI", "CL", "CLX", "CMG", "CPB", "CTRA", "DOC", "ERIE", "FDS", "GDDY", "GIS", "INVH", "IT", "KMB", "LYB", "MAA", "MMC", "OKE", "OXY", "PCG", "PG", "PGR", "RVTY", "SLB", "TAP", "TRGP", "TSN", "UHS", "UPS", "WAT"], "dist_label": "Member", "histogram": [[{"color": "rgb(70, 18, 100)", "height": 38.0, "perc": 8.1}, {"color": "rgb(68, 51, 125)", "height": 100.0, "perc": 21.6}, {"color": "rgb(58, 80, 138)", "height": 38.0, "perc": 8.1}, {"color": "rgb(46, 107, 141)", "height": 38.0, "perc": 8.1}, {"color": "rgb(36, 131, 141)", "height": 38.0, "perc": 8.1}, {"color": "rgb(33, 155, 136)", "height": 38.0, "perc": 8.1}, {"color": "rgb(51, 178, 121)", "height": 25.0, "perc": 5.4}, {"color": "rgb(94, 199, 96)", "height": 50.0, "perc": 10.8}, {"color": "rgb(155, 215, 59)", "height": 63.0, "perc": 13.5}, {"color": "rgb(220, 226, 37)", "height": 38.0, "perc": 8.1}]], "node_id": "cube0_cluster0", "projection_stats": []}, "type": "circle"}, {"color": [[0.1057884231536926], [0.41023834683574023]], "id": "", "name": "cube0_cluster1", "size": 3, "tooltip": {"cluster_stats": {"above": [], "below": [], "size": 17}, "custom_tooltips": ["BAX", "BF-B", "CHTR", "CNC", "CPRT", "DOW", "ELV", "EMN", "FI", "FICO", "GPN", "KMX", "LKQ", "LULU", "MOH", "TPL", "UNH"], "dist_label": "Member", "histogram": [[{"color": "rgb(70, 18, 100)", "height": 0.0, "perc": 0.0}, {"color": "rgb(68, 51, 125)", "height": 100.0, "perc": 23.5}, {"color": "rgb(58, 80, 138)", "height": 50.0, "perc": 11.8}, {"color": "rgb(46, 107, 141)", "height": 100.0, "perc": 23.5}, {"color": "rgb(36, 131, 141)", "height": 25.0, "perc": 5.9}, {"color": "rgb(33, 155, 136)", "height": 75.0, "perc": 17.6}, {"color": "rgb(51, 178, 121)", "height": 25.0, "perc": 5.9}, {"color": "rgb(94, 199, 96)", "height": 0.0, "perc": 0.0}, {"color": "rgb(155, 215, 59)", "height": 25.0, "perc": 5.9}, {"color": "rgb(220, 226, 37)", "height": 25.0, "perc": 5.9}]], "node_id": "cube0_cluster1", "projection_stats": []}, "type": "circle"}, {"color": [[0.0], [0.5060175008632524]], "id": "", "name": "cube1_cluster0", "size": 6, "tooltip": {"cluster_stats": {"above": [], "below": [], "size": 237}, "custom_tooltips": ["A", "ABBV", "ABT", "ACGL", "ADBE", "ADM", "ADP", "AEE", "AEP", "AFL", "AIG", "AIZ", "AJG", "ALL", "AMCR", "AME", "AMGN", "AMP", "AMT", "AON", "AOS", "APD", "ATO", "AVB", "AVY", "AWK", "AZO", "BAC", "BALL", "BG", "BIIB", "BR", "BRK-B", "BSX", "BXP", "CARR", "CB", "CBOE", "CCI", "CDW", "CHD", "CINF", "CL", "CLX", "CMCSA", "CME", "CMS", "CNP", "COR", "COST", "CPB", "CPT", "CRM", "CTSH", "CVS", "CVX", "D", "DE", "DGX", "DHR", "DOC", "DOV", "DPZ", "DRI", "DTE", "DUK", "DVA", "ECL", "ED", "EG", "EIX", "EOG", "EQIX", "EQR", "ES", "ESS", "ETR", "EVRG", "EXC", "EXPD", "EXR", "F", "FDS", "FE", "FIS", "FITB", "FOX", "FOXA", "FRT", "FTNT", "FTV", "GDDY", "GEN", "GILD", "GIS", "GL", "GM", "GPC", "GWW", "HBAN", "HCA", "HD", "HIG", "HON", "HRL", "HSIC", "HSY", "IBM", "ICE", "IFF", "INVH", "IPG", "IR", "IRM", "ITW", "J", "JBHT", "JKHY", "K", "KDP", "KEY", "KHC", "KIM", "KMB", "KMI", "KO", "KR", "KVUE", "L", "LEN", "LII", "LIN", "LMT", "LNT", "LOW", "MA", "MAA", "MAR", "MAS", "MCD", "MCK", "MCO", "MDLZ", "MDT", "MET", "MHK", "MKC", "MMC", "MMM", "MNST", "MO", "MRK", "MSCI", "MSI", "MTB", "MTCH", "NDSN", "NEE", "NI", "NVR", "O", "OMC", "ORLY", "PAYC", "PAYX", "PCAR", "PEG", "PEP", "PFE", "PG", "PGR", "PHM", "PKG", "PLD", "PM", "PNC", "PNW", "POOL", "PPL", "PRU", "PSA", "PSKY", "REG", "ROL", "ROP", "ROST", "RSG", "SBAC", "SHW", "SNA", "SO", "SOLV", "SPG", "SPGI", "SRE", "STLD", "STZ", "SYK", "SYY", "T", "TAP", "TFC", "TGT", "TJX", "TKO", "TMUS", "TRV", "TSCO", "TSN", "TTWO", "TXT", "TYL", "UDR", "UNP", "USB", "V", "VICI", "VLTO", "VRSK", "VRTX", "VTR", "VTRS", "VZ", "WAB", "WDAY", "WEC", "WELL", "WFC", "WM", "WMB", "WRB", "WTW", "WY", "XEL", "XOM", "YUM", "ZTS"], "dist_label": "Member", "histogram": [[{"color": "rgb(70, 18, 100)", "height": 96.0, "perc": 11.4}, {"color": "rgb(68, 51, 125)", "height": 75.0, "perc": 8.9}, {"color": "rgb(58, 80, 138)", "height": 71.0, "perc": 8.4}, {"color": "rgb(46, 107, 141)", "height": 89.0, "perc": 10.5}, {"color": "rgb(36, 131, 141)", "height": 75.0, "perc": 8.9}, {"color": "rgb(33, 155, 136)", "height": 100.0, "perc": 11.8}, {"color": "rgb(51, 178, 121)", "height": 71.0, "perc": 8.4}, {"color": "rgb(94, 199, 96)", "height": 89.0, "perc": 10.5}, {"color": "rgb(155, 215, 59)", "height": 79.0, "perc": 9.3}, {"color": "rgb(220, 226, 37)", "height": 100.0, "perc": 11.8}]], "node_id": "cube1_cluster0", "projection_stats": []}, "type": "circle"}, {"color": [[0.001996007984031936], [0.44914337990685294]], "id": "", "name": "cube1_cluster1", "size": 5, "tooltip": {"cluster_stats": {"above": [], "below": [], "size": 96}, "custom_tooltips": ["AAPL", "ACN", "AES", "AKAM", "ALB", "ALGN", "APA", "APO", "APP", "APTV", "ARE", "BAX", "BBY", "BDX", "BF-B", "BKR", "BLDR", "BMY", "BRO", "BX", "CAG", "CHTR", "CI", "CMG", "CNC", "COO", "COP", "CPAY", "CPRT", "CTRA", "DAY", "DD", "DECK", "DOW", "DVN", "EFX", "ELV", "EMN", "EPAM", "EQT", "ERIE", "EXE", "FANG", "FCX", "FDX", "FI", "FICO", "GEHC", "GPN", "GRMN", "HAL", "HPQ", "HUM", "IEX", "INTC", "IP", "IQV", "IT", "KMX", "LKQ", "LLY", "LULU", "LUV", "LYB", "MRNA", "MTD", "NXPI", "ODFL", "OKE", "OTIS", "OXY", "PANW", "PCG", "PFG", "PPG", "PSX", "PYPL", "QCOM", "REGN", "RVTY", "SBUX", "SJM", "SLB", "SW", "SWK", "TECH", "TMO", "TPL", "TRGP", "TSLA", "TXN", "UHS", "UPS", "VLO", "WAT", "ZBH"], "dist_label": "Member", "histogram": [[{"color": "rgb(70, 18, 100)", "height": 79.0, "perc": 11.5}, {"color": "rgb(68, 51, 125)", "height": 100.0, "perc": 14.6}, {"color": "rgb(58, 80, 138)", "height": 71.0, "perc": 10.4}, {"color": "rgb(46, 107, 141)", "height": 93.0, "perc": 13.5}, {"color": "rgb(36, 131, 141)", "height": 71.0, "perc": 10.4}, {"color": "rgb(33, 155, 136)", "height": 43.0, "perc": 6.2}, {"color": "rgb(51, 178, 121)", "height": 36.0, "perc": 5.2}, {"color": "rgb(94, 199, 96)", "height": 71.0, "perc": 10.4}, {"color": "rgb(155, 215, 59)", "height": 79.0, "perc": 11.5}, {"color": "rgb(220, 226, 37)", "height": 43.0, "perc": 6.2}]], "node_id": "cube1_cluster1", "projection_stats": []}, "type": "circle"}, {"color": [[0.0], [0.49809285538512016]], "id": "", "name": "cube2_cluster0", "size": 6, "tooltip": {"cluster_stats": {"above": [], "below": [], "size": 292}, "custom_tooltips": ["A", "ABBV", "ABT", "ACGL", "ACN", "ADBE", "ADM", "ADP", "AEE", "AEP", "AFL", "AIG", "AIZ", "AJG", "AKAM", "ALL", "AMCR", "AME", "AMGN", "AMP", "AMT", "AON", "AOS", "APD", "ARE", "ATO", "AVB", "AVY", "AWK", "AZO", "BALL", "BAX", "BBY", "BDX", "BF-B", "BG", "BIIB", "BKR", "BLDR", "BR", "BRK-B", "BRO", "BSX", "BXP", "CB", "CBOE", "CCI", "CDW", "CHD", "CHTR", "CINF", "CL", "CLX", "CMCSA", "CME", "CMG", "CMS", "CNP", "COO", "COP", "COR", "COST", "CPAY", "CPRT", "CPT", "CRM", "CTAS", "CTRA", "CTSH", "CVS", "CVX", "D", "DAY", "DD", "DE", "DECK", "DGX", "DHR", "DOC", "DOV", "DPZ", "DRI", "DTE", "DUK", "DVA", "DVN", "ECL", "ED", "EG", "EIX", "EMN", "EOG", "EPAM", "EQIX", "EQR", "EQT", "ERIE", "ES", "ESS", "ETR", "EVRG", "EW", "EXC", "EXE", "EXPD", "EXR", "FANG", "FDS", "FDX", "FE", "FIS", "FITB", "FOX", "FOXA", "FRT", "FTNT", "FTV", "GD", "GDDY", "GEHC", "GILD", "GIS", "GL", "GPC", "GPN", "GWW", "HAL", "HBAN", "HCA", "HD", "HIG", "HON", "HPQ", "HRL", "HSIC", "HST", "HSY", "HUM", "IBM", "ICE", "IEX", "IFF", "INVH", "IP", "IPG", "IR", "ISRG", "IT", "ITW", "J", "JBHT", "JKHY", "JNJ", "K", "KDP", "KHC", "KIM", "KMB", "KMI", "KO", "KR", "KVUE", "L", "LDOS", "LEN", "LH", "LII", "LIN", "LKQ", "LMT", "LNT", "LOW", "LULU", "MA", "MAA", "MAR", "MAS", "MCD", "MCK", "MCO", "MDLZ", "MDT", "MET", "MHK", "MKC", "MLM", "MMC", "MMM", "MNST", "MO", "MRK", "MSCI", "MSI", "MTB", "MTCH", "NEE", "NI", "NVR", "O", "ODFL", "OKE", "OMC", "ORLY", "OTIS", "OXY", "PAYX", "PCAR", "PEG", "PEP", "PFE", "PFG", "PG", "PGR", "PKG", "PLD", "PM", "PNC", "PNW", "POOL", "PPG", "PPL", "PRU", "PSA", "PSKY", "REG", "REGN", "ROL", "ROP", "ROST", "RSG", "RVTY", "SBAC", "SBUX", "SHW", "SJM", "SLB", "SNA", "SO", "SOLV", "SPG", "SPGI", "SRE", "STE", "STLD", "STZ", "SW", "SYK", "SYY", "T", "TDY", "TFC", "TGT", "TJX", "TKO", "TMO", "TMUS", "TRGP", "TRV", "TSCO", "TSN", "TTWO", "TYL", "UDR", "UHS", "UNP", "UPS", "USB", "V", "VICI", "VLTO", "VRSK", "VRSN", "VRTX", "VTR", "VTRS", "VZ", "WAB", "WAT", "WDAY", "WEC", "WELL", "WFC", "WM", "WMB", "WRB", "WTW", "WY", "XEL", "XOM", "YUM", "ZBH", "ZTS"], "dist_label": "Member", "histogram": [[{"color": "rgb(70, 18, 100)", "height": 91.0, "perc": 10.3}, {"color": "rgb(68, 51, 125)", "height": 85.0, "perc": 9.6}, {"color": "rgb(58, 80, 138)", "height": 88.0, "perc": 9.9}, {"color": "rgb(46, 107, 141)", "height": 100.0, "perc": 11.3}, {"color": "rgb(36, 131, 141)", "height": 85.0, "perc": 9.6}, {"color": "rgb(33, 155, 136)", "height": 97.0, "perc": 11.0}, {"color": "rgb(51, 178, 121)", "height": 67.0, "perc": 7.5}, {"color": "rgb(94, 199, 96)", "height": 85.0, "perc": 9.6}, {"color": "rgb(155, 215, 59)", "height": 91.0, "perc": 10.3}, {"color": "rgb(220, 226, 37)", "height": 97.0, "perc": 11.0}]], "node_id": "cube2_cluster0", "projection_stats": []}, "type": "circle"}, {"color": [[0.001996007984031936], [0.5025925161171909]], "id": "", "name": "cube2_cluster1", "size": 6, "tooltip": {"cluster_stats": {"above": [], "below": [], "size": 174}, "custom_tooltips": ["AAPL", "ABNB", "ADI", "ADSK", "AES", "ALB", "ALGN", "ALLE", "AMAT", "AMZN", "ANET", "APA", "APO", "APP", "APTV", "AXON", "AXP", "BA", "BAC", "BEN", "BK", "BKNG", "BLK", "BX", "C", "CAH", "CARR", "CAT", "CBRE", "CCL", "CDNS", "CEG", "CF", "CFG", "CHRW", "CMI", "COF", "CRL", "CRWD", "CSCO", "CSGP", "CSX", "CTVA", "DAL", "DASH", "DDOG", "DELL", "DG", "DHI", "DIS", "DLR", "DLTR", "DXCM", "EFX", "EL", "EMR", "ETN", "EXPE", "F", "FAST", "FCX", "FFIV", "FSLR", "GE", "GEN", "GLW", "GM", "GNRC", "GOOG", "GOOGL", "GRMN", "GS", "HAS", "HII", "HLT", "HOLX", "HPE", "HUBB", "HWM", "IBKR", "IDXX", "INCY", "INTC", "INTU", "IQV", "IRM", "IVZ", "JCI", "JPM", "KEY", "KEYS", "KKR", "KLAC", "LHX", "LLY", "LRCX", "LUV", "LVS", "LW", "LYV", "MCHP", "META", "MGM", "MOS", "MPC", "MPWR", "MRNA", "MS", "MTD", "MU", "NCLH", "NDAQ", "NDSN", "NEM", "NFLX", "NKE", "NOC", "NOW", "NSC", "NTAP", "NTRS", "NUE", "NWS", "NWSA", "NXPI", "ON", "PANW", "PAYC", "PH", "PHM", "PNR", "PODD", "PSX", "PYPL", "QCOM", "RF", "RJF", "RL", "RMD", "ROK", "RTX", "SCHW", "SMCI", "SNPS", "STT", "SWK", "SWKS", "SYF", "TDG", "TECH", "TER", "TPR", "TRMB", "TROW", "TSLA", "TT", "TTD", "TXN", "TXT", "UAL", "UBER", "ULTA", "URI", "VLO", "VMC", "VST", "WBD", "WMT", "WSM", "WST", "WYNN", "XYL", "XYZ", "ZBRA"], "dist_label": "Member", "histogram": [[{"color": "rgb(70, 18, 100)", "height": 75.0, "perc": 10.3}, {"color": "rgb(68, 51, 125)", "height": 75.0, "perc": 10.3}, {"color": "rgb(58, 80, 138)", "height": 71.0, "perc": 9.8}, {"color": "rgb(46, 107, 141)", "height": 50.0, "perc": 6.9}, {"color": "rgb(36, 131, 141)", "height": 88.0, "perc": 12.1}, {"color": "rgb(33, 155, 136)", "height": 63.0, "perc": 8.6}, {"color": "rgb(51, 178, 121)", "height": 100.0, "perc": 13.8}, {"color": "rgb(94, 199, 96)", "height": 67.0, "perc": 9.2}, {"color": "rgb(155, 215, 59)", "height": 67.0, "perc": 9.2}, {"color": "rgb(220, 226, 37)", "height": 71.0, "perc": 9.8}]], "node_id": "cube2_cluster1", "projection_stats": []}, "type": "circle"}, {"color": [[0.001996007984031936], [0.512691597936203]], "id": "", "name": "cube3_cluster0", "size": 6, "tooltip": {"cluster_stats": {"above": [], "below": [], "size": 212}, "custom_tooltips": ["AAPL", "ABNB", "ABT", "ADM", "ADP", "ADSK", "AEE", "AEP", "AKAM", "ALLE", "AME", "AMP", "AMZN", "AOS", "APD", "APTV", "ATO", "AXP", "BAC", "BALL", "BK", "BKNG", "BKR", "BLK", "BR", "BSX", "BXP", "CAH", "CARR", "CBOE", "CBRE", "CCI", "CDW", "CF", "CFG", "CINF", "CME", "CMI", "CNP", "COR", "COST", "CSCO", "CSGP", "CSX", "CTAS", "CTSH", "CTVA", "D", "DAY", "DE", "DGX", "DHR", "DIS", "DLR", "DOV", "DPZ", "DRI", "DTE", "DUK", "ECL", "EFX", "ES", "ETR", "EVRG", "EW", "F", "FAST", "FE", "FFIV", "FIS", "FITB", "FOX", "FOXA", "FTNT", "GD", "GEN", "GILD", "GL", "GM", "GOOG", "GOOGL", "GPC", "GRMN", "HBAN", "HD", "HIG", "HII", "HLT", "HOLX", "HON", "HST", "HSY", "HUBB", "IBM", "ICE", "INCY", "INTU", "IR", "IRM", "ISRG", "ITW", "J", "JNJ", "JPM", "KEY", "KEYS", "KIM", "KR", "L", "LDOS", "LEN", "LH", "LHX", "LII", "LIN", "LLY", "LNT", "LW", "LYV", "MA", "MAR", "MAS", "MCK", "MCO", "MDT", "MET", "MLM", "MMM", "MNST", "MO", "MOS", "MS", "MSCI", "MSI", "MTB", "MTCH", "MTD", "NDAQ", "NDSN", "NEE", "NFLX", "NI", "NOC", "NSC", "NTAP", "NUE", "NVR", "NWS", "NWSA", "ORLY", "PANW", "PAYC", "PCAR", "PEG", "PH", "PHM", "PKG", "PM", "PNC", "PNR", "PPG", "PSKY", "PSX", "PYPL", "RF", "RJF", "RMD", "ROL", "ROST", "RTX", "SBAC", "SCHW", "SO", "SPG", "SPGI", "SRE", "STE", "STLD", "STT", "SW", "SYK", "SYY", "T", "TDG", "TDY", "TFC", "TJX", "TKO", "TROW", "TSCO", "TT", "TTWO", "TXT", "TYL", "UBER", "UNP", "USB", "V", "VICI", "VLO", "VLTO", "VMC", "VRSN", "WAB", "WDAY", "WELL", "WFC", "WMB", "WMT", "WRB", "XEL", "XYL"], "dist_label": "Member", "histogram": [[{"color": "rgb(70, 18, 100)", "height": 72.0, "perc": 8.5}, {"color": "rgb(68, 51, 125)", "height": 84.0, "perc": 9.9}, {"color": "rgb(58, 80, 138)", "height": 84.0, "perc": 9.9}, {"color": "rgb(46, 107, 141)", "height": 64.0, "perc": 7.5}, {"color": "rgb(36, 131, 141)", "height": 96.0, "perc": 11.3}, {"color": "rgb(33, 155, 136)", "height": 96.0, "perc": 11.3}, {"color": "rgb(51, 178, 121)", "height": 100.0, "perc": 11.8}, {"color": "rgb(94, 199, 96)", "height": 84.0, "perc": 9.9}, {"color": "rgb(155, 215, 59)", "height": 84.0, "perc": 9.9}, {"color": "rgb(220, 226, 37)", "height": 84.0, "perc": 9.9}]], "node_id": "cube3_cluster0", "pr

## Acomodo de indices

In [19]:
graphs={
    'Historic1': graph_hist_1,
    'Sharpe': G,
    'Volatilidad': G_vol,
    'Retorno': G_ret,
    'PCA': G_pca}


graph_names = list(graphs.keys())

categories = {ticker: ticker_info_db[ticker]['sector'] for ticker in ticker_names}
market_caps = {ticker: ticker_info_db[ticker]['market_cap'] for ticker in ticker_names}

In [22]:
"""
Analiza todos los clusters encontrados en los diferentes archivos Mapper
"""
print("📊 ANALIZANDO TODOS LOS CLUSTERS DEL MAPPER")
print("=" * 60)

# Diccionario para almacenar todos los clusters encontrados
def extract_clusters_from_all_graphs(graphs_dict, ticker_names, min_cluster_size=2):
    """
    Extrae clusters de todos los grafos en el diccionario graphs.
    
    Parámetros:
    -----------
    graphs_dict : dict
        Diccionario con {graph_label: graph_object}
    ticker_names : list
        Lista de nombres de tickers
    min_cluster_size : int
        Tamaño mínimo de cluster (default: 2)
    
    Retorna:
    --------
    all_clusters : dict
        Diccionario con todos los clusters encontrados
    """
    all_clusters = {}
    total_clusters = 0
    
    for graph_label, graph in graphs_dict.items():
        print(f"\n🔍 Extrayendo clusters del análisis por {graph_label}:")
        print(f"   Total de nodos: {len(graph['nodes'])}")
        
        clusters_in_graph = 0
        for i, (node_name, node_indices) in enumerate(graph['nodes'].items()):
            if len(node_indices) >= min_cluster_size:
                cluster_tickers = [ticker_names[idx] for idx in node_indices]
                cluster_name = f"{graph_label}_Cluster_{i+1}"
                all_clusters[cluster_name] = {
                    'tickers': cluster_tickers,
                    'type': graph_label,
                    'node_name': node_name,
                    'size': len(cluster_tickers)
                }
                print(f"     -{cluster_name}: {cluster_tickers} ({len(cluster_tickers)} tickers)")
                clusters_in_graph += 1
        
        print(f"   📌 {clusters_in_graph} clusters encontrados en {graph_label}")
        total_clusters += clusters_in_graph
    
    print(f"\n{'='*60}")
    print(f"📋 RESUMEN TOTAL: {total_clusters} clusters encontrados en {len(graphs_dict)} grafos")
    print(f"{'='*60}")
    
    return all_clusters


# Ejecutar la extracción para todos los grafos
all_clusters = extract_clusters_from_all_graphs(
    graphs_dict=graphs,
    ticker_names=ticker_names,
    min_cluster_size=4
)

📊 ANALIZANDO TODOS LOS CLUSTERS DEL MAPPER
============================================================

🔍 Extrayendo clusters del análisis por Historic1:
   Total de nodos: 33
     -Historic1_Cluster_4: ['AXON', 'BLK', 'GS', 'INTU', 'KLAC', 'META', 'MPWR', 'NOW', 'PH', 'URI'] (10 tickers)
     -Historic1_Cluster_5: ['ADI', 'AMD', 'AVGO', 'BA', 'CEG', 'COIN', 'DASH', 'DDOG', 'DELL', 'GE', 'HOOD', 'HWM', 'JBL', 'JPM', 'MU', 'NRG', 'NVDA', 'ORCL', 'PLTR', 'RCL', 'RL', 'STX', 'TEL', 'TXN', 'VST'] (25 tickers)
     -Historic1_Cluster_6: ['APP', 'CAT', 'CRWD', 'EME', 'ETN', 'GEV', 'HUBB', 'IDXX', 'MSFT', 'PWR', 'ROK', 'SNPS', 'TSLA', 'TT', 'ULTA', 'ZBRA'] (16 tickers)
     -Historic1_Cluster_7: ['A', 'ABNB', 'ABT', 'ACGL', 'ADM', 'AEE', 'AEP', 'AES', 'AFL', 'AIG', 'AKAM', 'ALB', 'ALLE', 'AMCR', 'AMD', 'ANET', 'AOS', 'APA', 'APH', 'APO', 'APTV', 'ARE', 'ATO', 'AWK', 'BAC', 'BALL', 'BAX', 'BBY', 'BEN', 'BF-B', 'BG', 'BIIB', 'BK', 'BKR', 'BLDR', 'BMY', 'BRO', 'BSX', 'BX', 'BXP', 'C', 'CAG', 'CAH', 'CARR', 'CBRE', 'CCI', 'CCL', 'CF', 'CFG', 'CHD', 'CHRW', 'CINF', 'CL', 'CLX', 'CMCSA', 'CMG', 'CMS', 'CNC', 'CNP', 'COO', 'COP', 'CPB', 'CPRT', 'CPT', 'CRL', 'CSCO', 'CSGP', 'CSX', 'CTRA', 'CTSH', 'CTVA', 'CVS', 'CVX', 'D', 'DAL', 'DAY', 'DD', 'DDOG', 'DECK', 'DELL', 'DG', 'DHI', 'DIS', 'DLTR', 'DOC', 'DOW', 'DTE', 'DUK', 'DVA', 'DVN', 'DXCM', 'EBAY', 'ED', 'EIX', 'EL', 'EMN', 'EMR', 'EOG', 'EQR', 'EQT', 'ES', 'ETR', 'EVRG', 'EW', 'EXC', 'EXE', 'EXPD', 'EXR', 'F', 'FANG', 'FAST', 'FCX', 'FE', 'FIS', 'FITB', 'FOX', 'FOXA', 'FRT', 'FSLR', 'FTNT', 'FTV', 'GEHC', 'GEN', 'GILD', 'GIS', 'GL', 'GLW', 'GM', 'GNRC', 'GPC', 'GPN', 'HAL', 'HAS', 'HBAN', 'HIG', 'HOLX', 'HOOD', 'HPE', 'HPQ', 'HRL', 'HSIC', 'HST', 'HWM', 'IBKR', 'IFF', 'INCY', 'INTC', 'INVH', 'IP', 'IPG', 'IQV', 'IR', 'IRM', 'IVZ', 'J', 'JBHT', 'JCI', 'JNJ', 'K', 'KDP', 'KEY', 'KEYS', 'KHC', 'KIM', 'KKR', 'KMB', 'KMI', 'KMX', 'KO', 'KR', 'KVUE', 'L', 'LDOS', 'LEN', 'LKQ', 'LNT', 'LRCX', 'LUV', 'LVS', 'LW', 'LYB', 'LYV', 'MAA', 'MAS', 'MCHP', 'MDLZ', 'MDT', 'MET', 'MGM', 'MHK', 'MKC', 'MMM', 'MNST', 'MO', 'MOS', 'MPC', 'MRK', 'MRNA', 'MS', 'MTCH', 'MU', 'NCLH', 'NDAQ', 'NEE', 'NEM', 'NI', 'NKE', 'NRG', 'NTAP', 'NTRS', 'NUE', 'NVDA', 'NWS', 'NWSA', 'O', 'ODFL', 'OKE', 'OMC', 'ON', 'ORLY', 'OTIS', 'OXY', 'PAYX', 'PCAR', 'PCG', 'PEG', 'PEP', 'PFE', 'PFG', 'PG', 'PHM', 'PLD', 'PLTR', 'PNR', 'PNW', 'PPG', 'PPL', 'PRU', 'PSKY', 'PSX', 'PYPL', 'QCOM', 'REG', 'RF', 'RJF', 'ROL', 'ROST', 'RTX', 'RVTY', 'SBUX', 'SCHW', 'SJM', 'SLB', 'SMCI', 'SO', 'SOLV', 'SPG', 'SRE', 'STLD', 'STT', 'STX', 'SW', 'SWK', 'SWKS', 'SYF', 'SYY', 'T', 'TAP', 'TECH', 'TEL', 'TER', 'TFC', 'TGT', 'TJX', 'TPR', 'TRMB', 'TROW', 'TSCO', 'TSN', 'TTD', 'TXT', 'UAL', 'UBER', 'UDR', 'UPS', 'USB', 'VICI', 'VLO', 'VLTO', 'VST', 'VTR', 'VTRS', 'VZ', 'WBD', 'WDC', 'WEC', 'WELL', 'WFC', 'WMB', 'WMT', 'WRB', 'WSM', 'WY', 'WYNN', 'XEL', 'XOM', 'XYL', 'XYZ', 'YUM', 'ZBH', 'ZTS'] (311 tickers)
     -Historic1_Cluster_8: ['AMP', 'BLK', 'CRWD', 'DE', 'DPZ', 'EME', 'EQIX', 'FDS', 'GS', 'GWW', 'IDXX', 'INTU', 'ISRG', 'IT', 'LII', 'LIN', 'LMT', 'MA', 'MCK', 'MCO', 'META', 'MLM', 'MPWR', 'MSCI', 'MSFT', 'MSI', 'NOC', 'NOW', 'PH', 'ROP', 'SNPS', 'SPGI', 'TDY', 'TMO', 'TT', 'TYL', 'ULTA', 'VRTX'] (38 tickers)
     -Historic1_Cluster_9: ['AAPL', 'ABBV', 'ACN', 'ADBE', 'ADI', 'ADP', 'ADSK', 'AIZ', 'AJG', 'ALGN', 'ALL', 'AMAT', 'AME', 'AMGN', 'AMT', 'AMZN', 'AON', 'APD', 'APP', 'AVB', 'AVGO', 'AVY', 'AXP', 'BA', 'BDX', 'BR', 'CAT', 'CB', 'CBOE', 'CDNS', 'CDW', 'CEG', 'CHTR', 'CI', 'CME', 'CMI', 'COF', 'COR', 'CPAY', 'CRM', 'CTAS', 'DASH', 'DGX', 'DHR', 'DLR', 'DOV', 'DRI', 'ECL', 'EFX', 'EG', 'EPAM', 'ESS', 'ETN', 'EXPE', 'FDX', 'FFIV', 'FI', 'GD', 'GDDY', 'GE', 'GOOG', 'GOOGL', 'GRMN', 'HCA', 'HD', 'HII', 'HLT', 'HON', 'HSY', 'HUBB', 'HUM', 'IBM', 'ICE', 'IEX', 'ITW', 'JBL', 'JKHY', 'JPM', 'LH', 'LHX', 'LOW', 'LULU', 'MAR', 'MCD', 'MMC', 'MTB', 'NDSN', 'NSC', 'NXPI', 'ORCL', 'PANW', 'PAYC', 'PGR', 'PKG', 'PM', 'PNC', 'PODD', 'POOL', 'PSA', 'PTC', 'PWR', 'RCL', 'RL', 'RMD', 'ROK', 'RSG', 'SBAC', 'SHW', 'SNA', 'STE', 'STZ', 'SYK', 'TKO', 'TMUS', 'TRGP', 'TRV', 'TSLA', 'TTWO', 'TXN', 'UHS', 'UNP', 'V', 'VMC', 'VRSK', 'VRSN', 'WAB', 'WAT', 'WDAY', 'WM', 'WST', 'WTW', 'ZBRA'] (132 tickers)
     -Historic1_Cluster_10: ['A', 'ABNB', 'ABT', 'ACGL', 'ADM', 'AEE', 'AEP', 'AES', 'AFL', 'AIG', 'AKAM', 'ALB', 'ALLE', 'AMCR', 'ANET', 'AOS', 'APA', 'APH', 'APO', 'APTV', 'ARE', 'ATO', 'AWK', 'BAC', 'BALL', 'BAX', 'BBY', 'BEN', 'BF-B', 'BG', 'BIIB', 'BK', 'BKR', 'BLDR', 'BMY', 'BRO', 'BSX', 'BX', 'BXP', 'C', 'CAG', 'CAH', 'CARR', 'CBRE', 'CCI', 'CCL', 'CF', 'CFG', 'CHD', 'CHRW', 'CINF', 'CL', 'CLX', 'CMCSA', 'CMG', 'CMS', 'CNC', 'CNP', 'COO', 'COP', 'CPB', 'CPRT', 'CPT', 'CRL', 'CSCO', 'CSGP', 'CSX', 'CTRA', 'CTSH', 'CTVA', 'CVS', 'CVX', 'D', 'DAL', 'DAY', 'DD', 'DECK', 'DG', 'DHI', 'DIS', 'DLTR', 'DOC', 'DOW', 'DTE', 'DUK', 'DVA', 'DVN', 'DXCM', 'EBAY', 'ED', 'EIX', 'EL', 'EMN', 'EMR', 'EOG', 'EQR', 'EQT', 'ES', 'ETR', 'EVRG', 'EW', 'EXC', 'EXE', 'EXPD', 'EXR', 'F', 'FANG', 'FAST', 'FCX', 'FE', 'FIS', 'FITB', 'FOX', 'FOXA', 'FRT', 'FSLR', 'FTNT', 'FTV', 'GEHC', 'GEN', 'GILD', 'GIS', 'GL', 'GLW', 'GM', 'GNRC', 'GPC', 'GPN', 'HAL', 'HAS', 'HBAN', 'HIG', 'HOLX', 'HPE', 'HPQ', 'HRL', 'HSIC', 'HST', 'IBKR', 'IFF', 'INCY', 'INTC', 'INVH', 'IP', 'IPG', 'IQV', 'IR', 'IRM', 'IVZ', 'J', 'JBHT', 'JCI', 'JNJ', 'K', 'KDP', 'KEY', 'KEYS', 'KHC', 'KIM', 'KKR', 'KMB', 'KMI', 'KMX', 'KO', 'KR', 'KVUE', 'L', 'LDOS', 'LEN', 'LKQ', 'LNT', 'LRCX', 'LUV', 'LVS', 'LW', 'LYB', 'LYV', 'MAA', 'MAS', 'MCHP', 'MDLZ', 'MDT', 'MET', 'MGM', 'MHK', 'MKC', 'MMM', 'MNST', 'MO', 'MOS', 'MPC', 'MRK', 'MRNA', 'MS', 'MTCH', 'NCLH', 'NDAQ', 'NEE', 'NEM', 'NI', 'NKE', 'NTAP', 'NTRS', 'NUE', 'NWS', 'NWSA', 'O', 'OKE', 'OMC', 'ON', 'ORLY', 'OTIS', 'OXY', 'PAYX', 'PCAR', 'PCG', 'PEG', 'PEP', 'PFE', 'PFG', 'PHM', 'PLD', 'PNR', 'PNW', 'PPG', 'PPL', 'PRU', 'PSKY', 'PSX', 'PYPL', 'QCOM', 'REG', 'RF', 'RJF', 'ROL', 'ROST', 'RTX', 'RVTY', 'SBUX', 'SCHW', 'SJM', 'SLB', 'SMCI', 'SO', 'SOLV', 'SPG', 'SRE', 'STLD', 'STT', 'SW', 'SWK', 'SWKS', 'SYF', 'SYY', 'T', 'TAP', 'TECH', 'TER', 'TFC', 'TGT', 'TJX', 'TPR', 'TRMB', 'TROW', 'TSCO', 'TSN', 'TTD', 'TXT', 'UAL', 'UBER', 'UDR', 'UPS', 'USB', 'VICI', 'VLO', 'VLTO', 'VTR', 'VTRS', 'VZ', 'WBD', 'WDC', 'WEC', 'WELL', 'WFC', 'WMB', 'WMT', 'WRB', 'WY', 'WYNN', 'XEL', 'XOM', 'XYL', 'XYZ', 'YUM', 'ZBH', 'ZTS'] (296 tickers)
     -Historic1_Cluster_11: ['AMP', 'BRK-B', 'COST', 'DE', 'DPZ', 'EQIX', 'FDS', 'GWW', 'ISRG', 'IT', 'LII', 'LIN', 'LLY', 'LMT', 'MA', 'MCK', 'MCO', 'MLM', 'MSCI', 'MSI', 'NOC', 'REGN', 'ROP', 'SPGI', 'TDY', 'TMO', 'TYL', 'VRTX'] (28 tickers)
     -Historic1_Cluster_12: ['AAPL', 'ABBV', 'ACN', 'ADBE', 'ADP', 'ADSK', 'AIZ', 'AJG', 'ALGN', 'ALL', 'AMAT', 'AME', 'AMGN', 'AMT', 'AMZN', 'AON', 'APD', 'AVB', 'AVY', 'AXP', 'BDX', 'BR', 'CB', 'CBOE', 'CDNS', 'CDW', 'CHTR', 'CI', 'CME', 'CMI', 'COF', 'COR', 'CPAY', 'CRM', 'CTAS', 'DGX', 'DHR', 'DLR', 'DOV', 'DRI', 'ECL', 'EFX', 'EG', 'ELV', 'EPAM', 'ERIE', 'ESS', 'EXPE', 'FDX', 'FFIV', 'FI', 'GD', 'GDDY', 'GOOG', 'GOOGL', 'GRMN', 'HCA', 'HD', 'HII', 'HLT', 'HON', 'HSY', 'HUM', 'IBM', 'ICE', 'IEX', 'ITW', 'JKHY', 'LH', 'LHX', 'LOW', 'LULU', 'MAR', 'MCD', 'MMC', 'MOH', 'MTB', 'NDSN', 'NSC', 'NXPI', 'ODFL', 'PANW', 'PAYC', 'PG', 'PGR', 'PKG', 'PM', 'PNC', 'PODD', 'POOL', 'PSA', 'PTC', 'RMD', 'RSG', 'SBAC', 'SHW', 'SNA', 'STE', 'STZ', 'SYK', 'TKO', 'TMUS', 'TRGP', 'TRV', 'TTWO', 'UHS', 'UNP', 'V', 'VMC', 'VRSK', 'VRSN', 'WAB', 'WAT', 'WDAY', 'WM', 'WSM', 'WST', 'WTW'] (118 tickers)
     -Historic1_Cluster_14: ['ELV', 'ERIE', 'MOH', 'UNH'] (4 tickers)
     -Historic1_Cluster_19: ['CRWD', 'EME', 'GEV', 'HUBB', 'IDXX', 'MSFT', 'SNPS', 'TT', 'ULTA'] (9 tickers)
     -Historic1_Cluster_20: ['BLK', 'MTD', 'NFLX', 'NOW', 'TDG'] (5 tickers)
     -Historic1_Cluster_21: ['AXON', 'GS', 'INTU', 'KLAC', 'META', 'MPWR', 'PH', 'URI'] (8 tickers)
     -Historic1_Cluster_22: ['EQIX', 'GS', 'INTU', 'LII', 'MA', 'MCK', 'META', 'MPWR', 'MSCI', 'PH', 'ROP', 'TYL'] (12 tickers)
     -Historic1_Cluster_23: ['BLK', 'GWW', 'MTD', 'NOW', 'TDG'] (5 tickers)
     -Historic1_Cluster_24: ['ADBE', 'AMP', 'CHTR', 'CRWD', 'DE', 'DPZ', 'EME', 'FDS', 'HUBB', 'IDXX', 'ISRG', 'IT', 'LIN', 'LMT', 'MCO', 'MLM', 'MSFT', 'MSI', 'NOC', 'SNPS', 'SPGI', 'SYK', 'TDY', 'TMO', 'TT', 'ULTA', 'VRTX'] (27 tickers)
     -Historic1_Cluster_25: ['AMP', 'BRK-B', 'DE', 'ISRG', 'LII', 'MA', 'MCK', 'MLM', 'MSCI', 'NOC', 'REGN', 'ROP', 'SPGI', 'TDY', 'TYL'] (15 tickers)
     -Historic1_Cluster_26: ['COST', 'EQIX', 'GWW', 'LLY'] (4 tickers)
     -Historic1_Cluster_27: ['ADBE', 'CHTR', 'DPZ', 'ELV', 'FDS', 'IT', 'LIN', 'LMT', 'MCO', 'MSI', 'SYK', 'TMO', 'VRTX'] (13 tickers)
   📌 19 clusters encontrados en Historic1

🔍 Extrayendo clusters del análisis por Sharpe:
   Total de nodos: 12
     -Sharpe_Cluster_1: ['BMY', 'BRO', 'CAG', 'CI', 'CLX', 'CPB', 'CPRT', 'GIS', 'IT', 'MMC', 'TAP', 'TSN', 'ZBH'] (13 tickers)
     -Sharpe_Cluster_2: ['BAX', 'CNC', 'ELV', 'EMN', 'FI', 'LKQ', 'MOH', 'UNH'] (8 tickers)
     -Sharpe_Cluster_3: ['ACGL', 'ACN', 'ADBE', 'AFL', 'AIG', 'AIZ', 'AJG', 'AON', 'ARE', 'AVB', 'AVY', 'BMY', 'BRK-B', 'CB', 'CHD', 'CI', 'CL', 'CLX', 'CMCSA', 'COO', 'COP', 'CPB', 'CPT', 'CTRA', 'CTSH', 'CVX', 'DOC', 'DVA', 'ED', 'EG', 'EOG', 'EQR', 'ERIE', 'ESS', 'EXE', 'FDS', 'FDX', 'FTV', 'GDDY', 'GIS', 'GWW', 'HRL', 'IEX', 'IFF', 'INVH', 'IP', 'IT', 'JKHY', 'K', 'KDP', 'KHC', 'KMB', 'KO', 'KVUE', 'MAA', 'MDLZ', 'MET', 'MKC', 'MMC', 'MRK', 'ODFL', 'OKE', 'OMC', 'OTIS', 'PAYX', 'PCG', 'PEP', 'PFG', 'PG', 'PGR', 'PRU', 'PSA', 'ROP', 'RSG', 'RVTY', 'SBUX', 'STZ', 'TAP', 'TMUS', 'TSN', 'UDR', 'UHS', 'UNP', 'UPS', 'VRSK', 'WTW', 'WY', 'XOM', 'YUM', 'ZBH', 'ZTS'] (91 tickers)
     -Sharpe_Cluster_4: ['BAX', 'BDX', 'BF-B', 'BRO', 'CHTR', 'CMG', 'CNC', 'CPRT', 'DOW', 'DVN', 'ELV', 'EMN', 'FI', 'FICO', 'GEHC', 'GPN', 'HAL', 'HPQ', 'KMX', 'LKQ', 'LULU', 'LYB', 'MOH', 'OXY', 'SLB', 'TPL', 'TRGP', 'UNH', 'WAT'] (29 tickers)
     -Sharpe_Cluster_5: ['A', 'ABBV', 'ABT', 'ACGL', 'ADBE', 'ADP', 'AEE', 'AFL', 'AIG', 'AIZ', 'AJG', 'ALL', 'AMCR', 'AME', 'AMGN', 'AMP', 'AMT', 'AON', 'APD', 'ATO', 'AVB', 'AVY', 'AWK', 'AZO', 'BG', 'BIIB', 'BR', 'BRK-B', 'BSX', 'BXP', 'CB', 'CCI', 'CDW', 'CHD', 'CINF', 'CL', 'CMCSA', 'CMS', 'COR', 'COST', 'CPT', 'CRM', 'CTSH', 'CVS', 'CVX', 'DE', 'DGX', 'DHR', 'DOC', 'DOV', 'DPZ', 'DRI', 'DTE', 'DUK', 'DVA', 'ECL', 'ED', 'EG', 'EIX', 'EOG', 'EQIX', 'EQR', 'ES', 'ESS', 'ETR', 'EVRG', 'EXC', 'EXPD', 'EXR', 'FDS', 'FIS', 'FITB', 'FOX', 'FOXA', 'FRT', 'FTNT', 'FTV', 'GDDY', 'GEN', 'GILD', 'GL', 'GWW', 'HBAN', 'HCA', 'HD', 'HIG', 'HON', 'HRL', 'HSIC', 'HST', 'IBM', 'IEX', 'IFF', 'INVH', 'IPG', 'ISRG', 'ITW', 'JBHT', 'JKHY', 'K', 'KDP', 'KEYS', 'KHC', 'KIM', 'KMB', 'KMI', 'KO', 'KR', 'KVUE', 'L', 'LEN', 'LII', 'LIN', 'LMT', 'LNT', 'LOW', 'MA', 'MAA', 'MAR', 'MAS', 'MCD', 'MCK', 'MCO', 'MDLZ', 'MDT', 'MET', 'MHK', 'MKC', 'MMM', 'MNST', 'MRK', 'MSCI', 'MSI', 'MTB', 'MTCH', 'NDSN', 'NEE', 'NVR', 'O', 'OMC', 'ORLY', 'OTIS', 'PAYX', 'PCAR', 'PCG', 'PEP', 'PFE', 'PG', 'PGR', 'PKG', 'PLD', 'PM', 'PNW', 'POOL', 'PPL', 'PRU', 'PSA', 'REG', 'ROP', 'ROST', 'RSG', 'SBAC', 'SHW', 'SNA', 'SO', 'SOLV', 'SPG', 'SPGI', 'STE', 'STZ', 'SYK', 'T', 'TFC', 'TJX', 'TMUS', 'TRV', 'TSCO', 'TTWO', 'TXT', 'TYL', 'UDR', 'UNP', 'USB', 'V', 'VICI', 'VRSK', 'VRSN', 'VRTX', 'VTR', 'VTRS', 'VZ', 'WAB', 'WEC', 'WM', 'WMB', 'WRB', 'WTW', 'WY', 'XEL', 'XOM', 'YUM', 'ZTS'] (202 tickers)
     -Sharpe_Cluster_6: ['AAPL', 'ABNB', 'ACN', 'AES', 'AKAM', 'ALB', 'ALGN', 'APA', 'APO', 'ARE', 'AXP', 'BBY', 'BDX', 'BF-B', 'BKR', 'BLDR', 'CARR', 'CHTR', 'CMG', 'COO', 'COP', 'CPAY', 'CTRA', 'DAY', 'DD', 'DECK', 'DOW', 'DVN', 'EFX', 'EPAM', 'EQT', 'ERIE', 'EXE', 'EXPE', 'FANG', 'FCX', 'FDX', 'FICO', 'GEHC', 'GPN', 'GRMN', 'HAL', 'HPQ', 'HUM', 'INTC', 'IP', 'IQV', 'IR', 'KMX', 'LLY', 'LULU', 'LUV', 'LW', 'LYB', 'MRNA', 'MTD', 'NXPI', 'ODFL', 'OKE', 'OXY', 'PANW', 'PAYC', 'PFG', 'PODD', 'PPG', 'PSX', 'PYPL', 'QCOM', 'REGN', 'RVTY', 'SBUX', 'SJM', 'SLB', 'STLD', 'SW', 'SWK', 'SWKS', 'TECH', 'TGT', 'TMO', 'TPL', 'TRGP', 'TSLA', 'TXN', 'UHS', 'UPS', 'VLO', 'WAT', 'WDAY', 'WST'] (90 tickers)
     -Sharpe_Cluster_7: ['A', 'ABBV', 'ABT', 'ADM', 'ADP', 'ADSK', 'AEE', 'AEP', 'AKAM', 'ALL', 'AMCR', 'AME', 'AMGN', 'AMP', 'AMT', 'AMZN', 'AOS', 'APD', 'ATO', 'AWK', 'AZO', 'BAC', 'BALL', 'BEN', 'BG', 'BIIB', 'BK', 'BKNG', 'BLK', 'BR', 'BSX', 'BXP', 'CAH', 'CBOE', 'CBRE', 'CCI', 'CDW', 'CF', 'CFG', 'CINF', 'CME', 'CMI', 'CMS', 'CNP', 'COR', 'COST', 'CRM', 'CSCO', 'CSGP', 'CSX', 'CTAS', 'CTVA', 'CVS', 'D', 'DE', 'DGX', 'DHR', 'DIS', 'DLR', 'DOV', 'DPZ', 'DRI', 'DTE', 'DUK', 'ECL', 'EIX', 'EQIX', 'EQT', 'ES', 'ETR', 'EVRG', 'EW', 'EXC', 'EXPD', 'EXR', 'F', 'FAST', 'FE', 'FFIV', 'FIS', 'FITB', 'FOX', 'FOXA', 'FRT', 'FTNT', 'GD', 'GEN', 'GILD', 'GL', 'GM', 'GOOG', 'GOOGL', 'GPC', 'GS', 'HBAN', 'HCA', 'HD', 'HIG', 'HLT', 'HON', 'HSIC', 'HST', 'HSY', 'IBM', 'ICE', 'INCY', 'IPG', 'IR', 'IRM', 'ISRG', 'ITW', 'J', 'JBHT', 'JNJ', 'JPM', 'KEY', 'KEYS', 'KIM', 'KMI', 'KR', 'L', 'LDOS', 'LEN', 'LH', 'LII', 'LIN', 'LMT', 'LNT', 'LOW', 'LYV', 'MA', 'MAR', 'MAS', 'MCD', 'MCK', 'MCO', 'MDT', 'MHK', 'MLM', 'MMM', 'MNST', 'MO', 'MS', 'MSCI', 'MSI', 'MTB', 'MTCH', 'NDSN', 'NEE', 'NFLX', 'NI', 'NOC', 'NSC', 'NTRS', 'NVR', 'NWS', 'NWSA', 'O', 'ORLY', 'PCAR', 'PEG', 'PFE', 'PHM', 'PKG', 'PLD', 'PM', 'PNC', 'PNR', 'PNW', 'POOL', 'PPL', 'PSKY', 'REG', 'RF', 'RJF', 'ROL', 'ROST', 'RTX', 'SBAC', 'SHW', 'SJM', 'SNA', 'SO', 'SOLV', 'SPG', 'SPGI', 'SRE', 'STE', 'STLD', 'STT', 'SYK', 'SYY', 'T', 'TDG', 'TDY', 'TFC', 'TGT', 'TJX', 'TKO', 'TMO', 'TRMB', 'TROW', 'TRV', 'TSCO', 'TTWO', 'TXT', 'TYL', 'UBER', 'USB', 'V', 'VICI', 'VLTO', 'VMC', 'VRSN', 'VRTX', 'VTR', 'VTRS', 'VZ', 'WAB', 'WDAY', 'WEC', 'WELL', 'WFC', 'WM', 'WMB', 'WMT', 'WRB', 'XEL', 'XYL'] (229 tickers)
     -Sharpe_Cluster_8: ['AAPL', 'ABNB', 'ADI', 'AES', 'ALB', 'ALGN', 'AMAT', 'APA', 'APO', 'APP', 'APTV', 'AXON', 'AXP', 'BA', 'BBY', 'BKR', 'BLDR', 'BX', 'CARR', 'CHRW', 'COF', 'CPAY', 'CRL', 'CRWD', 'DAL', 'DASH', 'DAY', 'DD', 'DDOG', 'DECK', 'DELL', 'DG', 'DHI', 'DXCM', 'EFX', 'EL', 'EPAM', 'EXPE', 'FANG', 'FCX', 'FSLR', 'GRMN', 'HAS', 'HOLX', 'HPE', 'HUM', 'IDXX', 'INTC', 'IQV', 'IVZ', 'KKR', 'KLAC', 'LLY', 'LRCX', 'LUV', 'LVS', 'LW', 'MCHP', 'META', 'MGM', 'MPC', 'MPWR', 'MRNA', 'MTD', 'MU', 'NCLH', 'NEM', 'NKE', 'NOW', 'NTAP', 'NUE', 'NXPI', 'ON', 'PANW', 'PAYC', 'PH', 'PODD', 'PPG', 'PSX', 'PTC', 'PYPL', 'QCOM', 'REGN', 'RL', 'SMCI', 'SW', 'SWK', 'SWKS', 'SYF', 'TECH', 'TER', 'TSLA', 'TTD', 'TXN', 'UAL', 'VLO', 'WBD', 'WSM', 'WST', 'WYNN', 'XYZ', 'ZBRA'] (102 tickers)
     -Sharpe_Cluster_9: ['AMAT', 'AMD', 'ANET', 'APP', 'AVGO', 'AXON', 'BA', 'BX', 'CCL', 'CEG', 'COIN', 'CRL', 'CRWD', 'DAL', 'DASH', 'DDOG', 'DELL', 'DLTR', 'EL', 'FSLR', 'GNRC', 'HPE', 'HWM', 'IBKR', 'IVZ', 'JBL', 'KKR', 'KLAC', 'LRCX', 'LVS', 'MCHP', 'MPWR', 'MU', 'NCLH', 'NRG', 'NVDA', 'ON', 'ORCL', 'PLTR', 'RCL', 'SMCI', 'STX', 'SYF', 'TER', 'TPR', 'TTD', 'UAL', 'VST', 'WBD', 'WDC', 'WYNN', 'XYZ', 'ZBRA'] (53 tickers)
     -Sharpe_Cluster_10: ['ADI', 'ADM', 'ADSK', 'AEP', 'ALLE', 'AMZN', 'AOS', 'APTV', 'BAC', 'BALL', 'BEN', 'BK', 'BKNG', 'BLK', 'C', 'CAH', 'CAT', 'CBOE', 'CBRE', 'CDNS', 'CF', 'CFG', 'CHRW', 'CME', 'CMI', 'CNP', 'COF', 'CSCO', 'CSGP', 'CSX', 'CTAS', 'CTVA', 'D', 'DG', 'DHI', 'DIS', 'DLR', 'DXCM', 'EBAY', 'EMR', 'ETN', 'EW', 'F', 'FAST', 'FE', 'FFIV', 'GD', 'GE', 'GLW', 'GM', 'GOOG', 'GOOGL', 'GPC', 'GS', 'HAS', 'HII', 'HLT', 'HOLX', 'HSY', 'HUBB', 'ICE', 'IDXX', 'INCY', 'INTU', 'IRM', 'J', 'JCI', 'JNJ', 'JPM', 'KEY', 'LDOS', 'LH', 'LYV', 'META', 'MGM', 'MLM', 'MO', 'MOS', 'MPC', 'MS', 'MSFT', 'NDAQ', 'NEM', 'NFLX', 'NI', 'NKE', 'NOC', 'NOW', 'NSC', 'NTAP', 'NTRS', 'NUE', 'NWS', 'NWSA', 'PEG', 'PH', 'PHM', 'PNC', 'PNR', 'PSKY', 'PTC', 'PWR', 'RF', 'RJF', 'RL', 'RMD', 'ROK', 'ROL', 'RTX', 'SCHW', 'SNPS', 'SRE', 'STT', 'SYY', 'TDG', 'TDY', 'TEL', 'TKO', 'TRMB', 'TROW', 'TT', 'UBER', 'ULTA', 'URI', 'VLTO', 'VMC', 'WELL', 'WFC', 'WMT', 'WSM', 'XYL'] (131 tickers)
     -Sharpe_Cluster_11: ['AMD', 'ANET', 'AVGO', 'CCL', 'CEG', 'COIN', 'GEV', 'HOOD', 'JBL', 'NRG', 'NVDA', 'ORCL', 'PLTR', 'RCL', 'STX', 'VST', 'WDC'] (17 tickers)
     -Sharpe_Cluster_12: ['ALLE', 'APH', 'C', 'CAT', 'CDNS', 'DLTR', 'EBAY', 'EME', 'EMR', 'ETN', 'GE', 'GLW', 'GNRC', 'HII', 'HUBB', 'HWM', 'IBKR', 'INTU', 'JCI', 'LHX', 'MOS', 'MSFT', 'NDAQ', 'PWR', 'RMD', 'ROK', 'SCHW', 'SNPS', 'TEL', 'TPR', 'TT', 'ULTA', 'URI'] (33 tickers)
   📌 12 clusters encontrados en Sharpe

🔍 Extrayendo clusters del análisis por Volatilidad:
   Total de nodos: 24
     -Volatilidad_Cluster_1: ['K', 'KO', 'MCD', 'O', 'PNW'] (5 tickers)
     -Volatilidad_Cluster_2: ['CMS', 'CNP', 'DUK', 'FE', 'SO', 'WEC'] (6 tickers)
     -Volatilidad_Cluster_4: ['AFL', 'AIG', 'AJG', 'AMCR', 'AON', 'AVB', 'AVY', 'BRK-B', 'CAG', 'CB', 'CHD', 'CL', 'CLX', 'CMCSA', 'CPB', 'CPT', 'DOC', 'DVA', 'EG', 'EQR', 'FDS', 'FRT', 'GIS', 'HRL', 'INVH', 'IT', 'JKHY', 'KDP', 'KHC', 'KMB', 'KVUE', 'MAA', 'MKC', 'MMC', 'PEP', 'PG', 'PSA', 'REG', 'ROP', 'SHW', 'STZ', 'TAP', 'TSN', 'UDR', 'UNP', 'VRSK', 'WTW', 'YUM'] (48 tickers)
     -Volatilidad_Cluster_5: ['BK', 'CAH', 'CSCO', 'CSX', 'CTAS', 'CTVA', 'DLR', 'EW', 'FAST', 'GD', 'JNJ', 'LDOS', 'LHX', 'MLM', 'MSFT', 'NDAQ', 'NWS', 'NWSA', 'RMD', 'SCHW', 'SRE', 'STE', 'TDG', 'TDY', 'VMC', 'WMT'] (26 tickers)
     -Volatilidad_Cluster_6: ['ABT', 'ADP', 'AEE', 'AEP', 'AME', 'AMT', 'ATO', 'AWK', 'AZO', 'BALL', 'BR', 'BSX', 'CBOE', 'CCI', 'CME', 'CMS', 'CNP', 'COR', 'COST', 'D', 'DGX', 'DPZ', 'DRI', 'DTE', 'DUK', 'ECL', 'ED', 'ES', 'ETR', 'EVRG', 'EXC', 'FE', 'GWW', 'HCA', 'HD', 'HIG', 'HSIC', 'HSY', 'ICE', 'ITW', 'J', 'KIM', 'KMI', 'KO', 'L', 'LIN', 'LNT', 'LOW', 'MA', 'MCD', 'MCK', 'MDLZ', 'MDT', 'MNST', 'MO', 'MSI', 'NI', 'O', 'ORLY', 'PEG', 'PFE', 'PM', 'PNW', 'PPL', 'PSKY', 'ROL', 'RSG', 'SBAC', 'SO', 'SPGI', 'SYK', 'SYY', 'T', 'TJX', 'TRV', 'V', 'VICI', 'VLTO', 'VRTX', 'VTR', 'VZ', 'WEC', 'WELL', 'WM', 'WRB', 'XEL'] (86 tickers)
     -Volatilidad_Cluster_7: ['A', 'ABBV', 'ABT', 'ADM', 'ADP', 'ALL', 'AMCR', 'AME', 'AMGN', 'AMP', 'AMT', 'AOS', 'APD', 'AVY', 'AWK', 'AZO', 'BALL', 'BG', 'BIIB', 'BR', 'BSX', 'BXP', 'CBOE', 'CCI', 'CDW', 'CINF', 'CMCSA', 'COR', 'CRM', 'CTAS', 'CTSH', 'CVS', 'D', 'DE', 'DGX', 'DOV', 'DPZ', 'DRI', 'DVA', 'ES', 'EW', 'EXR', 'F', 'FIS', 'FITB', 'FOX', 'FOXA', 'FRT', 'GEN', 'GILD', 'GL', 'GM', 'GPC', 'HBAN', 'HCA', 'HD', 'HIG', 'HON', 'HSIC', 'HST', 'HSY', 'IBM', 'IFF', 'IPG', 'IRM', 'ITW', 'J', 'KIM', 'KMI', 'KR', 'L', 'LEN', 'LH', 'LII', 'LIN', 'LOW', 'MA', 'MAR', 'MCK', 'MCO', 'MDLZ', 'MET', 'MMM', 'MRK', 'MSCI', 'MSI', 'MTB', 'MTCH', 'NDSN', 'NEE', 'NVR', 'ORLY', 'PCAR', 'PFE', 'PKG', 'PLD', 'PM', 'POOL', 'PPG', 'PRU', 'PSA', 'PSKY', 'REG', 'ROL', 'ROST', 'RSG', 'SBAC', 'SHW', 'SOLV', 'SPG', 'SPGI', 'STE', 'SYK', 'T', 'TFC', 'TKO', 'TRV', 'TSCO', 'TTWO', 'TXT', 'TYL', 'UNP', 'USB', 'V', 'VLTO', 'VRSN', 'VTRS', 'WAB', 'WFC', 'WMB', 'WRB', 'XEL', 'XOM', 'ZTS'] (134 tickers)
     -Volatilidad_Cluster_8: ['ACGL', 'ACN', 'ADBE', 'AFL', 'AIG', 'AIZ', 'AJG', 'AON', 'ARE', 'AVB', 'BMY', 'BRO', 'CAG', 'CB', 'CHD', 'CI', 'CLX', 'CPB', 'CPRT', 'CPT', 'CTRA', 'CVX', 'DOC', 'EG', 'EIX', 'EOG', 'EQIX', 'EQR', 'ERIE', 'ESS', 'EXE', 'EXPD', 'FDS', 'FTV', 'GDDY', 'GIS', 'GWW', 'IEX', 'IT', 'JKHY', 'KHC', 'KVUE', 'LMT', 'MAA', 'MKC', 'MMC', 'OMC', 'OTIS', 'PAYX', 'PCG', 'PEP', 'PFG', 'PGR', 'ROP', 'SJM', 'SNA', 'STZ', 'TMUS', 'TSN', 'UDR', 'UPS', 'VRSK', 'VRTX', 'WTW', 'WY', 'YUM', 'ZBH'] (67 tickers)

### Pesos

In [23]:
# Convert market_caps dict to pandas Series
market_caps_series = pd.Series(market_caps)

# Mostrar muestra del DataFrame
print(f"\n📋 Muestra de las capitalizaciones:")
print(market_caps_series.head(10))
print(f"\n📊 Estadísticas de las capitalizaciones:")
print(f"   💰 Capitalización promedio: ${market_caps_series.mean():,.0f}")
print(f"   📈 Capitalización máxima: ${market_caps_series.max():,.0f}")
print(f"   📉 Capitalización mínima: ${market_caps_series.min():,.0f}")

📋 Muestra de las capitalizaciones:
A         40642621440
AAPL    4027681603584
ABBV     403128582144
ABNB      77349847040
ABT      216983027712
ACGL      31830286336
ACN      154569621504
ADBE     142005862400
ADI      114576416768
ADM       29159389184
dtype: int64

📊 Estadísticas de las capitalizaciones:
   💰 Capitalización promedio: $129,751,684,256
   📈 Capitalización máxima: $4,939,762,892,800
   📉 Capitalización mínima: $6,148,401,664

In [24]:
def create_market_cap_weighted_index(cluster_tickers, data, market_caps_dict, start_value=1):
    """
    Crea un índice ponderado por capitalización de mercado para un cluster específico.
    
    Parámetros:
    -----------
    cluster_tickers : list
        Lista de tickers del cluster
    data : pd.DataFrame
        DataFrame con precios históricos (tickers como columnas)
    market_caps_dict : dict
        Diccionario con {ticker: market_cap}
    start_value : float
        Valor inicial del índice (default: 1)
    
    Retorna:
    --------
    index_series : pd.Series
        Serie temporal del índice
    weights : dict
        Diccionario con los pesos de cada ticker
    """
    # Filtrar tickers que existen tanto en data como en market_caps
    valid_tickers = [t for t in cluster_tickers if t in data.columns and t in market_caps_dict]
    
    if not valid_tickers:
        print(f"⚠️  No hay tickers válidos en el cluster")
        return None, None
    
    # Calcular capitalización total del cluster
    total_market_cap = sum([market_caps_dict[ticker] for ticker in valid_tickers])
    
    # Calcular pesos de cada ticker (capitalización / capitalización total)
    weights = {ticker: market_caps_dict[ticker] / total_market_cap for ticker in valid_tickers}
    
    # Crear el índice
    index_series = pd.Series(0, index=data.index)
    
    for ticker, weight in weights.items():
        # Normalizar precios del ticker al valor inicial
        ticker_prices = data[ticker].dropna()
        if len(ticker_prices) > 0:
            ticker_normalized = (ticker_prices / ticker_prices.iloc[0]) * start_value
            # Agregar al índice con su peso
            index_series = index_series.add(ticker_normalized * weight, fill_value=0)
    
    return index_series, weights


def create_all_cluster_indices(all_clusters, data, market_caps_dict, start_value=1):
    """
    Crea índices ponderados por capitalización para todos los clusters.
    
    Parámetros:
    -----------
    all_clusters : dict
        Diccionario con todos los clusters {cluster_name: {tickers: [...], ...}}
    data : pd.DataFrame
        DataFrame con precios históricos
    market_caps_dict : dict
        Diccionario con {ticker: market_cap}
    start_value : float
        Valor inicial del índice (default: 1)
    
    Retorna:
    --------
    cluster_indices : dict
        Diccionario con {cluster_name: {index: serie, weights: dict, metrics: dict}}
    """
    cluster_indices = {}
    
    
    
    for cluster_name, cluster_info in all_clusters.items():
        cluster_tickers = cluster_info['tickers']
        cluster_type = cluster_info['type']
        
        
        
        # Crear índice para este cluster
        index_series, weights = create_market_cap_weighted_index(
            cluster_tickers, data, market_caps_dict, start_value
        )
        
        if index_series is not None:
            # Calcular métricas del índice
            returns = index_series.pct_change().dropna()
            
            total_return = (index_series.iloc[-1] / index_series.iloc[0] - 1) * 1
            volatility = returns.std() * np.sqrt(252) * 1
            sharpe = (returns.mean() / returns.std() * np.sqrt(252)) if returns.std() > 0 else 0
            max_drawdown = ((index_series / index_series.cummax()) - 1).min() * 1
            
            metrics = {
                'retorno_total': total_return,
                'volatilidad': volatility,
                'sharpe_ratio': sharpe,
                'max_drawdown': max_drawdown,
                'valor_final': index_series.iloc[-1],
                'num_tickers': len(weights)
            }
            
            cluster_indices[cluster_name] = {
                'index': index_series,
                'weights': weights,
                'metrics': metrics,
                'type': cluster_type
            }
            
            
            
            # Mostrar los 3 tickers con mayor peso
            sorted_weights = sorted(weights.items(), key=lambda x: x[1], reverse=True)
            
        else:
            print(f"   ❌ No se pudo crear índice")
    
    
    
    return cluster_indices


def plot_cluster_indices(cluster_indices, benchmark_ticker='SPY', data=None, top_n=10):
    """
    Visualiza los índices de los clusters comparados con un benchmark.
    
    Parámetros:
    -----------
    cluster_indices : dict
        Diccionario con los índices de los clusters
    benchmark_ticker : str
        Ticker del benchmark (default: 'SPY')
    data : pd.DataFrame
        DataFrame con precios históricos (para obtener benchmark)
    top_n : int
        Número de mejores índices a resaltar (default: 10)
    """
    import matplotlib.pyplot as plt
    
    fig, axes = plt.subplots(2, 2, figsize=(18, 12))
    fig.suptitle('📊 Análisis de Índices Ponderados por Capitalización de Mercado', 
                 fontsize=16, fontweight='bold')
    
    # Subplot 1: Performance de todos los índices
    ax1 = axes[0, 0]
    for cluster_name, cluster_data in cluster_indices.items():
        ax1.plot(cluster_data['index'], alpha=0.3, linewidth=1)
    
    # Agregar benchmark si está disponible
    if data is not None and benchmark_ticker in data.columns:
        benchmark = (data[benchmark_ticker] / data[benchmark_ticker].iloc[0]) * 1
        ax1.plot(benchmark, color='red', linewidth=2, label=f'{benchmark_ticker} (Benchmark)', linestyle='--')
    
    ax1.set_title('Performance de Todos los Índices', fontweight='bold')
    ax1.set_xlabel('Fecha')
    ax1.set_ylabel('Valor del Índice (Base 1)')
    ax1.grid(True, alpha=0.3)
    ax1.legend()
    
    # Subplot 2: Top N índices por Sharpe Ratio
    ax2 = axes[0, 1]
    sorted_by_sharpe = sorted(cluster_indices.items(), 
                              key=lambda x: x[1]['metrics']['sharpe_ratio'], 
                              reverse=True)[:top_n]
    
    colors = plt.cm.viridis(np.linspace(0, 1, len(sorted_by_sharpe)))
    for i, (cluster_name, cluster_data) in enumerate(sorted_by_sharpe):
        ax2.plot(cluster_data['index'], label=f"{cluster_name}", 
                color=colors[i], linewidth=2, alpha=0.8)
    
    if data is not None and benchmark_ticker in data.columns:
        benchmark = (data[benchmark_ticker] / data[benchmark_ticker].iloc[0]) * 1
        ax2.plot(benchmark, color='red', linewidth=2, label=f'{benchmark_ticker}', linestyle='--')
    
    ax2.set_title(f'Top {top_n} Índices por Sharpe Ratio', fontweight='bold')
    ax2.set_xlabel('Fecha')
    ax2.set_ylabel('Valor del Índice (Base 100)')
    ax2.grid(True, alpha=0.3)
    ax2.legend(fontsize=8, loc='best')
    
    # Subplot 3: Retorno vs Volatilidad (Scatter)
    ax3 = axes[1, 0]
    returns = [data['metrics']['retorno_total'] for data in cluster_indices.values()]
    vols = [data['metrics']['volatilidad'] for data in cluster_indices.values()]
    sharpes = [data['metrics']['sharpe_ratio'] for data in cluster_indices.values()]
    
    scatter = ax3.scatter(vols, returns, c=sharpes, s=100, alpha=0.6, 
                         cmap='RdYlGn', edgecolors='black', linewidth=1)
    
    # Añadir benchmark si está disponible
    if data is not None and benchmark_ticker in data.columns:
        bench_returns = (data[benchmark_ticker].pct_change().dropna())
        bench_ret = (data[benchmark_ticker].iloc[-1] / data[benchmark_ticker].iloc[0] - 1) * 1
        bench_vol = bench_returns.std() * np.sqrt(252) * 1
        ax3.scatter(bench_vol, bench_ret, color='red', s=200, marker='*', 
                   edgecolors='black', linewidth=2, label=benchmark_ticker, zorder=5)
    
    ax3.set_title('Retorno vs Volatilidad (Frontera Eficiente)', fontweight='bold')
    ax3.set_xlabel('Volatilidad (%)')
    ax3.set_ylabel('Retorno Total (%)')
    ax3.grid(True, alpha=0.3)
    plt.colorbar(scatter, ax=ax3, label='Sharpe Ratio')
    ax3.legend()
    
    # Subplot 4: Métricas comparativas (barras)
    ax4 = axes[1, 1]
    cluster_names = list(cluster_indices.keys())[:15]  # Top 15 para legibilidad
    sharpe_values = [cluster_indices[name]['metrics']['sharpe_ratio'] for name in cluster_names]
    
    bars = ax4.barh(range(len(cluster_names)), sharpe_values, 
                    color=plt.cm.RdYlGn(np.linspace(0.3, 0.9, len(cluster_names))))
    ax4.set_yticks(range(len(cluster_names)))
    ax4.set_yticklabels(cluster_names, fontsize=8)
    ax4.set_xlabel('Sharpe Ratio')
    ax4.set_title(f'Comparación de Sharpe Ratios (Top 15)', fontweight='bold')
    ax4.grid(True, alpha=0.3, axis='x')
    
    # Añadir valores en las barras
    for i, bar in enumerate(bars):
        width = bar.get_width()
        ax4.text(width, bar.get_y() + bar.get_height()/2, 
                f'{width:.2f}', ha='left', va='center', fontsize=8)
    
    plt.tight_layout()
    plt.show()
    
    return fig


def export_cluster_indices_to_csv(cluster_indices, filename='cluster_indices.csv'):
    """
    Exporta los índices de todos los clusters a un archivo CSV.
    
    Parámetros:
    -----------
    cluster_indices : dict
        Diccionario con los índices de los clusters
    filename : str
        Nombre del archivo CSV (default: 'cluster_indices.csv')
    """
    # Crear DataFrame con todos los índices
    indices_df = pd.DataFrame()
    
    for cluster_name, cluster_data in cluster_indices.items():
        indices_df[cluster_name] = cluster_data['index']
    
    # Guardar a CSV
    indices_df.to_csv(filename)
    print(f"✅ Índices exportados a: {filename}")
    print(f"   Dimensiones: {indices_df.shape}")
    
    # También crear un archivo con las métricas
    metrics_filename = filename.replace('.csv', '_metrics.csv')
    metrics_data = []
    
    for cluster_name, cluster_data in cluster_indices.items():
        metrics = cluster_data['metrics'].copy()
        metrics['cluster_name'] = cluster_name
        metrics['type'] = cluster_data['type']
        metrics_data.append(metrics)
    
    metrics_df = pd.DataFrame(metrics_data)
    metrics_df = metrics_df[['cluster_name', 'type', 'retorno_total', 'volatilidad', 
                             'sharpe_ratio', 'max_drawdown', 'valor_final', 'num_tickers']]
    metrics_df.to_csv(metrics_filename, index=False)
    print(f"✅ Métricas exportadas a: {metrics_filename}")
    
    return indices_df, metrics_df


print("✅ Funciones de índices ponderados cargadas:")
print("   - create_market_cap_weighted_index()")
print("   - create_all_cluster_indices()")
print("   - plot_cluster_indices()")
print("   - export_cluster_indices_to_csv()")

✅ Funciones de índices ponderados cargadas:
   - create_market_cap_weighted_index()
   - create_all_cluster_indices()
   - plot_cluster_indices()
   - export_cluster_indices_to_csv()

In [25]:
# Paso 1: Verificar que tenemos todos los datos necesarios
print("🔍 Verificando datos necesarios...")
print(f"   ✓ all_clusters: {len(all_clusters)} clusters")
print(f"   ✓ tickers_data: {tickers_data.shape}")
print(f"   ✓ market_caps: {len(market_caps)} tickers con capitalización")

# Paso 2: Crear índices para todos los clusters
cluster_indices = create_all_cluster_indices(
    all_clusters=all_clusters,
    data=tickers_data,
    market_caps_dict=market_caps,
    start_value=1
)

# Paso 3: Crear tabla resumen con métricas
print("\n" + "=" * 100)
print("  RESUMEN DE ÍNDICES CREADOS")
print("=" * 100)

summary_data = []
for cluster_name, cluster_data in cluster_indices.items():
    summary_data.append({
        'Cluster': cluster_name,
        'Tipo': cluster_data['type'],
        'Tickers': cluster_data['metrics']['num_tickers'],
        'Retorno (%)': cluster_data['metrics']['retorno_total'],
        'Volatilidad (%)': cluster_data['metrics']['volatilidad'],
        'Sharpe Ratio': cluster_data['metrics']['sharpe_ratio'],
        'Max Drawdown (%)': cluster_data['metrics']['max_drawdown'],
        'Valor Final': cluster_data['metrics']['valor_final']
    })

summary_df = pd.DataFrame(summary_data)
summary_df = summary_df.sort_values('Sharpe Ratio', ascending=False)

print("\n📊 TOP 10 ÍNDICES POR SHARPE RATIO:")
print(summary_df.head(10).to_string(index=False))

print("\n\n📊 ESTADÍSTICAS GENERALES:")
print(f"   📈 Retorno promedio: {summary_df['Retorno (%)'].mean():.2f}%")
print(f"   📊 Volatilidad promedio: {summary_df['Volatilidad (%)'].mean():.2f}%")
print(f"   ⭐ Sharpe Ratio promedio: {summary_df['Sharpe Ratio'].mean():.2f}")
print(f"   📉 Max Drawdown promedio: {summary_df['Max Drawdown (%)'].mean():.2f}%")

🔍 Verificando datos necesarios...
   ✓ all_clusters: 64 clusters
   ✓ tickers_data: (85, 502)
   ✓ market_caps: 502 tickers con capitalización

====================================================================================================
  RESUMEN DE ÍNDICES CREADOS
====================================================================================================

📊 TOP 10 ÍNDICES POR SHARPE RATIO:
               Cluster        Tipo  Tickers  Retorno (%)  Volatilidad (%)  Sharpe Ratio  Max Drawdown (%)  Valor Final
  Historic1_Cluster_19   Historic1        9     0.393299         0.292140      3.552932         -0.078843     1.393299
Volatilidad_Cluster_18 Volatilidad       11     0.728738         0.502964      3.516987         -0.163629     1.728738
     Sharpe_Cluster_12      Sharpe       33     0.367401         0.281814      3.473541         -0.098782     1.367401
        PCA_Cluster_10         PCA       13     0.362216         0.285470      3.391444         -0.076326     1.362216
     Sharpe_Cluster_11      Sharpe       17     0.655900         0.487510      3.346130         -0.150871     1.655900
         PCA_Cluster_9         PCA       56     0.580630         0.449181      3.281723         -0.149485     1.580630
Volatilidad_Cluster_13 Volatilidad       17     0.623354         0.477517      3.281538         -0.148829     1.623354
Volatilidad_Cluster_21 Volatilidad        6     0.807848         0.595674      3.277123         -0.177678     1.807848
 Volatilidad_Cluster_5 Volatilidad       26     0.275735         0.235078      3.225926         -0.079080     1.275735
   Historic1_Cluster_5   Historic1       25     0.568756         0.460893      3.160060         -0.152781     1.568756


📊 ESTADÍSTICAS GENERALES:
   📈 Retorno promedio: 0.11%
   📊 Volatilidad promedio: 0.33%
   ⭐ Sharpe Ratio promedio: 0.68
   📉 Max Drawdown promedio: -0.16%

====================================================================================================
  RESUMEN DE ÍNDICES CREADOS
====================================================================================================

📊 TOP 10 ÍNDICES POR SHARPE RATIO:
               Cluster        Tipo  Tickers  Retorno (%)  Volatilidad (%)  Sharpe Ratio  Max Drawdown (%)  Valor Final
  Historic1_Cluster_19   Historic1        9     0.393299         0.292140      3.552932         -0.078843     1.393299
Volatilidad_Cluster_18 Volatilidad       11     0.728738         0.502964      3.516987         -0.163629     1.728738
     Sharpe_Cluster_12      Sharpe       33     0.367401         0.281814      3.473541         -0.098782     1.367401
        PCA_Cluster_10         PCA       13     0.362216         0.285470      3.391444         -0.076326     1.362216
     Sharpe_Cluster_11      Sharpe       17     0.655900         0.487510      3.346130         -0.150871     1.655900
         PCA_Cluster_9         PCA       56     0.580630         0.449181      3.281723         -0.149485     1.580630
Volatilidad_Cluster_13 Volatilidad       17     0.623354         0.477517      3.281538         -0.148829     1.623354
Volatilidad_Cluster_21 Volatilidad        6     0.807848         0.595674      3.277123         -0.177678     1.807848
 Volatilidad_Cluster_5 Volatilidad       26     0.275735         0.235078      3.225926         -0.079080     1.275735
   Historic1_Cluster_5   Historic1       25     0.568756         0.460893      3.160060         -0.152781     1.568756


📊 ESTADÍSTICAS GENERALES:
   📈 Retorno promedio: 0.11%
   📊 Volatilidad promedio: 0.33%
   ⭐ Sharpe Ratio promedio: 0.68
   📉 Max Drawdown promedio: -0.16%